//! Every source file the ONNX Runtime build compiles, listed out. These are
//! the lists upstream keeps in CMake, transcribed once so that no CMake, no
//! Python, and no configure step is needed to build the runtime.

const std = @import("std");

pub const protobuf_lite_sources = [_][]const u8{
    "src/google/protobuf/any_lite.cc",
    "src/google/protobuf/arena.cc",
    "src/google/protobuf/arenastring.cc",
    "src/google/protobuf/arenaz_sampler.cc",
    "src/google/protobuf/extension_set.cc",
    "src/google/protobuf/generated_enum_util.cc",
    "src/google/protobuf/generated_message_tctable_lite.cc",
    "src/google/protobuf/generated_message_util.cc",
    "src/google/protobuf/implicit_weak_message.cc",
    "src/google/protobuf/inlined_string_field.cc",
    "src/google/protobuf/io/coded_stream.cc",
    "src/google/protobuf/io/io_win32.cc",
    "src/google/protobuf/io/strtod.cc",
    "src/google/protobuf/io/zero_copy_stream.cc",
    "src/google/protobuf/io/zero_copy_stream_impl.cc",
    "src/google/protobuf/io/zero_copy_stream_impl_lite.cc",
    "src/google/protobuf/map.cc",
    "src/google/protobuf/message_lite.cc",
    "src/google/protobuf/parse_context.cc",
    "src/google/protobuf/repeated_field.cc",
    "src/google/protobuf/repeated_ptr_field.cc",
    "src/google/protobuf/stubs/bytestream.cc",
    "src/google/protobuf/stubs/common.cc",
    "src/google/protobuf/stubs/int128.cc",
    "src/google/protobuf/stubs/status.cc",
    "src/google/protobuf/stubs/statusor.cc",
    "src/google/protobuf/stubs/stringpiece.cc",
    "src/google/protobuf/stubs/stringprintf.cc",
    "src/google/protobuf/stubs/structurally_valid.cc",
    "src/google/protobuf/stubs/strutil.cc",
    "src/google/protobuf/stubs/time.cc",
    "src/google/protobuf/wire_format_lite.cc",
};

pub const protobuf_full_sources = [_][]const u8{
    "src/google/protobuf/any.cc",
    "src/google/protobuf/any.pb.cc",
    "src/google/protobuf/api.pb.cc",
    "src/google/protobuf/compiler/importer.cc",
    "src/google/protobuf/compiler/parser.cc",
    "src/google/protobuf/descriptor.cc",
    "src/google/protobuf/descriptor_database.cc",
    "src/google/protobuf/descriptor.pb.cc",
    "src/google/protobuf/duration.pb.cc",
    "src/google/protobuf/dynamic_message.cc",
    "src/google/protobuf/empty.pb.cc",
    "src/google/protobuf/extension_set_heavy.cc",
    "src/google/protobuf/field_mask.pb.cc",
    "src/google/protobuf/generated_message_bases.cc",
    "src/google/protobuf/generated_message_reflection.cc",
    "src/google/protobuf/generated_message_tctable_full.cc",
    "src/google/protobuf/io/gzip_stream.cc",
    "src/google/protobuf/io/printer.cc",
    "src/google/protobuf/io/tokenizer.cc",
    "src/google/protobuf/map_field.cc",
    "src/google/protobuf/message.cc",
    "src/google/protobuf/reflection_ops.cc",
    "src/google/protobuf/service.cc",
    "src/google/protobuf/source_context.pb.cc",
    "src/google/protobuf/struct.pb.cc",
    "src/google/protobuf/stubs/substitute.cc",
    "src/google/protobuf/text_format.cc",
    "src/google/protobuf/timestamp.pb.cc",
    "src/google/protobuf/type.pb.cc",
    "src/google/protobuf/unknown_field_set.cc",
    "src/google/protobuf/util/delimited_message_util.cc",
    "src/google/protobuf/util/field_comparator.cc",
    "src/google/protobuf/util/field_mask_util.cc",
    "src/google/protobuf/util/internal/datapiece.cc",
    "src/google/protobuf/util/internal/default_value_objectwriter.cc",
    "src/google/protobuf/util/internal/error_listener.cc",
    "src/google/protobuf/util/internal/field_mask_utility.cc",
    "src/google/protobuf/util/internal/json_escaping.cc",
    "src/google/protobuf/util/internal/json_objectwriter.cc",
    "src/google/protobuf/util/internal/json_stream_parser.cc",
    "src/google/protobuf/util/internal/object_writer.cc",
    "src/google/protobuf/util/internal/protostream_objectsource.cc",
    "src/google/protobuf/util/internal/protostream_objectwriter.cc",
    "src/google/protobuf/util/internal/proto_writer.cc",
    "src/google/protobuf/util/internal/type_info.cc",
    "src/google/protobuf/util/internal/utility.cc",
    "src/google/protobuf/util/json_util.cc",
    "src/google/protobuf/util/message_differencer.cc",
    "src/google/protobuf/util/time_util.cc",
    "src/google/protobuf/util/type_resolver_util.cc",
    "src/google/protobuf/wire_format.cc",
    "src/google/protobuf/wrappers.pb.cc",
};

pub const protoc_sources = [_][]const u8{
    "src/google/protobuf/compiler/code_generator.cc",
    "src/google/protobuf/compiler/command_line_interface.cc",
    "src/google/protobuf/compiler/cpp/enum.cc",
    "src/google/protobuf/compiler/cpp/enum_field.cc",
    "src/google/protobuf/compiler/cpp/extension.cc",
    "src/google/protobuf/compiler/cpp/field.cc",
    "src/google/protobuf/compiler/cpp/file.cc",
    "src/google/protobuf/compiler/cpp/generator.cc",
    "src/google/protobuf/compiler/cpp/helpers.cc",
    "src/google/protobuf/compiler/cpp/map_field.cc",
    "src/google/protobuf/compiler/cpp/message.cc",
    "src/google/protobuf/compiler/cpp/message_field.cc",
    "src/google/protobuf/compiler/cpp/padding_optimizer.cc",
    "src/google/protobuf/compiler/cpp/parse_function_generator.cc",
    "src/google/protobuf/compiler/cpp/primitive_field.cc",
    "src/google/protobuf/compiler/cpp/service.cc",
    "src/google/protobuf/compiler/cpp/string_field.cc",
    "src/google/protobuf/compiler/csharp/csharp_doc_comment.cc",
    "src/google/protobuf/compiler/csharp/csharp_enum.cc",
    "src/google/protobuf/compiler/csharp/csharp_enum_field.cc",
    "src/google/protobuf/compiler/csharp/csharp_field_base.cc",
    "src/google/protobuf/compiler/csharp/csharp_generator.cc",
    "src/google/protobuf/compiler/csharp/csharp_helpers.cc",
    "src/google/protobuf/compiler/csharp/csharp_map_field.cc",
    "src/google/protobuf/compiler/csharp/csharp_message.cc",
    "src/google/protobuf/compiler/csharp/csharp_message_field.cc",
    "src/google/protobuf/compiler/csharp/csharp_primitive_field.cc",
    "src/google/protobuf/compiler/csharp/csharp_reflection_class.cc",
    "src/google/protobuf/compiler/csharp/csharp_repeated_enum_field.cc",
    "src/google/protobuf/compiler/csharp/csharp_repeated_message_field.cc",
    "src/google/protobuf/compiler/csharp/csharp_repeated_primitive_field.cc",
    "src/google/protobuf/compiler/csharp/csharp_source_generator_base.cc",
    "src/google/protobuf/compiler/csharp/csharp_wrapper_field.cc",
    "src/google/protobuf/compiler/java/context.cc",
    "src/google/protobuf/compiler/java/doc_comment.cc",
    "src/google/protobuf/compiler/java/enum.cc",
    "src/google/protobuf/compiler/java/enum_field.cc",
    "src/google/protobuf/compiler/java/enum_field_lite.cc",
    "src/google/protobuf/compiler/java/enum_lite.cc",
    "src/google/protobuf/compiler/java/extension.cc",
    "src/google/protobuf/compiler/java/extension_lite.cc",
    "src/google/protobuf/compiler/java/field.cc",
    "src/google/protobuf/compiler/java/file.cc",
    "src/google/protobuf/compiler/java/generator.cc",
    "src/google/protobuf/compiler/java/generator_factory.cc",
    "src/google/protobuf/compiler/java/helpers.cc",
    "src/google/protobuf/compiler/java/kotlin_generator.cc",
    "src/google/protobuf/compiler/java/map_field.cc",
    "src/google/protobuf/compiler/java/map_field_lite.cc",
    "src/google/protobuf/compiler/java/message_builder.cc",
    "src/google/protobuf/compiler/java/message_builder_lite.cc",
    "src/google/protobuf/compiler/java/message.cc",
    "src/google/protobuf/compiler/java/message_field.cc",
    "src/google/protobuf/compiler/java/message_field_lite.cc",
    "src/google/protobuf/compiler/java/message_lite.cc",
    "src/google/protobuf/compiler/java/name_resolver.cc",
    "src/google/protobuf/compiler/java/primitive_field.cc",
    "src/google/protobuf/compiler/java/primitive_field_lite.cc",
    "src/google/protobuf/compiler/java/service.cc",
    "src/google/protobuf/compiler/java/shared_code_generator.cc",
    "src/google/protobuf/compiler/java/string_field.cc",
    "src/google/protobuf/compiler/java/string_field_lite.cc",
    "src/google/protobuf/compiler/objectivec/objectivec_enum.cc",
    "src/google/protobuf/compiler/objectivec/objectivec_enum_field.cc",
    "src/google/protobuf/compiler/objectivec/objectivec_extension.cc",
    "src/google/protobuf/compiler/objectivec/objectivec_field.cc",
    "src/google/protobuf/compiler/objectivec/objectivec_file.cc",
    "src/google/protobuf/compiler/objectivec/objectivec_generator.cc",
    "src/google/protobuf/compiler/objectivec/objectivec_helpers.cc",
    "src/google/protobuf/compiler/objectivec/objectivec_map_field.cc",
    "src/google/protobuf/compiler/objectivec/objectivec_message.cc",
    "src/google/protobuf/compiler/objectivec/objectivec_message_field.cc",
    "src/google/protobuf/compiler/objectivec/objectivec_oneof.cc",
    "src/google/protobuf/compiler/objectivec/objectivec_primitive_field.cc",
    "src/google/protobuf/compiler/php/php_generator.cc",
    "src/google/protobuf/compiler/plugin.cc",
    "src/google/protobuf/compiler/plugin.pb.cc",
    "src/google/protobuf/compiler/python/generator.cc",
    "src/google/protobuf/compiler/python/helpers.cc",
    "src/google/protobuf/compiler/python/pyi_generator.cc",
    "src/google/protobuf/compiler/ruby/ruby_generator.cc",
    "src/google/protobuf/compiler/subprocess.cc",
    "src/google/protobuf/compiler/zip_writer.cc",
};

pub const FileFlags = struct {
    file: []const u8,
    flags: []const []const u8,
};

const spin_pause_file = "core/common/spin_pause.cc";
const spin_pause_waitpkg = [_]FileFlags{.{ .file = spin_pause_file, .flags = &.{"-mwaitpkg"} }};
const spin_pause_plain = [_]FileFlags{.{ .file = spin_pause_file, .flags = &.{} }};

/// Every list whose contents depend on the machine being built for. One switch,
/// so an architecture is either described here in full or rejected outright.
pub const TargetSources = struct {
    cpuinfo: []const []const u8,
    /// The mlas sources written for this architecture, on top of
    /// `ort_mlas_sources`.
    mlas: []const []const u8,
    /// mlas translation units compiled against a raised ISA baseline.
    mlas_groups: []const MlasGroup,
    device_discovery: []const []const u8,
    /// Sources needing flags of their own. Zig's addCSourceFiles appends rather
    /// than overrides, so a file listed here must NOT also appear in a list
    /// elsewhere in this file: both objects would land in the archive and the
    /// linker would resolve against the first one added, silently discarding
    /// the flags.
    file_flags: []const FileFlags,
};

pub fn forTarget(target: std.Target) TargetSources {
    const is_darwin = target.os.tag.isDarwin();
    const device_discovery: []const []const u8 = if (is_darwin)
        &apple_device_discovery_sources
    else if (target.os.tag == .linux)
        &linux_device_discovery_sources
    else
        &default_device_discovery_sources;

    return switch (target.cpu.arch) {
        .x86_64 => .{
            .cpuinfo = if (is_darwin)
                &(cpuinfo_sources ++ cpuinfo_x86_sources ++ cpuinfo_x86_mach_sources ++ cpuinfo_mach_sources)
            else
                &(cpuinfo_sources ++ cpuinfo_x86_sources ++ cpuinfo_x86_linux_sources ++ cpuinfo_linux_sources),
            .mlas = &ort_mlas_x86_64_sources,
            .mlas_groups = &ort_mlas_x86_64_groups,
            .device_discovery = device_discovery,
            // spin_pause.cc reaches for umonitor/umwait, which only assemble
            // with -mwaitpkg; the instructions themselves stay behind a
            // runtime check.
            .file_flags = &spin_pause_waitpkg,
        },
        .aarch64 => .{
            .cpuinfo = if (is_darwin)
                &(cpuinfo_sources ++ cpuinfo_arm_sources ++ cpuinfo_arm_mach_sources ++ cpuinfo_mach_sources)
            else
                &(cpuinfo_sources ++ cpuinfo_arm_sources ++ cpuinfo_arm_linux_sources ++ cpuinfo_linux_sources),
            .mlas = &ort_mlas_aarch64_sources,
            .mlas_groups = &ort_mlas_aarch64_groups,
            .device_discovery = device_discovery,
            .file_flags = &spin_pause_plain,
        },
        else => std.debug.panic("unsupported architecture: {s}", .{@tagName(target.cpu.arch)}),
    };
}

pub const onnx_proto_sources = [_][]const u8{
    "onnx/onnx-ml.pb.cc",
    "onnx/onnx-operators-ml.pb.cc",
    "onnx/onnx-data.pb.cc",
};

pub const abseil_sources = [_][]const u8{
    "absl/base/internal/cycleclock.cc",
    "absl/base/internal/low_level_alloc.cc",
    "absl/base/internal/raw_logging.cc",
    "absl/base/internal/spinlock.cc",
    "absl/base/internal/spinlock_wait.cc",
    "absl/base/internal/strerror.cc",
    "absl/base/internal/sysinfo.cc",
    "absl/base/internal/thread_identity.cc",
    "absl/base/internal/throw_delegate.cc",
    "absl/base/internal/tracing.cc",
    "absl/base/internal/unscaledcycleclock.cc",
    "absl/base/log_severity.cc",
    "absl/container/internal/hashtablez_sampler.cc",
    "absl/container/internal/hashtablez_sampler_force_weak_definition.cc",
    "absl/container/internal/raw_hash_set.cc",
    "absl/crc/crc32c.cc",
    "absl/crc/internal/cpu_detect.cc",
    "absl/crc/internal/crc.cc",
    "absl/crc/internal/crc_cord_state.cc",
    "absl/crc/internal/crc_memcpy_fallback.cc",
    "absl/crc/internal/crc_memcpy_x86_arm_combined.cc",
    "absl/crc/internal/crc_non_temporal_memcpy.cc",
    "absl/crc/internal/crc_x86_arm_combined.cc",
    "absl/debugging/internal/address_is_readable.cc",
    "absl/debugging/internal/decode_rust_punycode.cc",
    "absl/debugging/internal/demangle.cc",
    "absl/debugging/internal/demangle_rust.cc",
    "absl/debugging/internal/elf_mem_image.cc",
    "absl/debugging/internal/examine_stack.cc",
    "absl/debugging/internal/utf8_for_code_point.cc",
    "absl/debugging/internal/vdso_support.cc",
    "absl/debugging/leak_check.cc",
    "absl/debugging/stacktrace.cc",
    "absl/debugging/symbolize.cc",
    "absl/flags/commandlineflag.cc",
    "absl/flags/internal/commandlineflag.cc",
    "absl/flags/internal/flag.cc",
    "absl/flags/internal/private_handle_accessor.cc",
    "absl/flags/internal/program_name.cc",
    "absl/flags/marshalling.cc",
    "absl/flags/reflection.cc",
    "absl/flags/usage_config.cc",
    "absl/hash/internal/city.cc",
    "absl/hash/internal/hash.cc",
    "absl/log/globals.cc",
    "absl/log/internal/check_op.cc",
    "absl/log/internal/conditions.cc",
    "absl/log/internal/fnmatch.cc",
    "absl/log/internal/globals.cc",
    "absl/log/internal/log_format.cc",
    "absl/log/internal/log_message.cc",
    "absl/log/internal/log_sink_set.cc",
    "absl/log/internal/nullguard.cc",
    "absl/log/internal/proto.cc",
    "absl/log/internal/structured_proto.cc",
    "absl/log/internal/vlog_config.cc",
    "absl/log/log_entry.cc",
    "absl/log/log_sink.cc",
    "absl/numeric/int128.cc",
    "absl/profiling/internal/exponential_biased.cc",
    "absl/strings/ascii.cc",
    "absl/strings/charconv.cc",
    "absl/strings/cord_analysis.cc",
    "absl/strings/cord.cc",
    "absl/strings/escaping.cc",
    "absl/strings/internal/charconv_bigint.cc",
    "absl/strings/internal/charconv_parse.cc",
    "absl/strings/internal/cord_internal.cc",
    "absl/strings/internal/cord_rep_btree.cc",
    "absl/strings/internal/cord_rep_btree_navigator.cc",
    "absl/strings/internal/cord_rep_btree_reader.cc",
    "absl/strings/internal/cord_rep_consume.cc",
    "absl/strings/internal/cord_rep_crc.cc",
    "absl/strings/internal/cordz_functions.cc",
    "absl/strings/internal/cordz_handle.cc",
    "absl/strings/internal/cordz_info.cc",
    "absl/strings/internal/damerau_levenshtein_distance.cc",
    "absl/strings/internal/escaping.cc",
    "absl/strings/internal/memutil.cc",
    "absl/strings/internal/ostringstream.cc",
    "absl/strings/internal/str_format/arg.cc",
    "absl/strings/internal/str_format/bind.cc",
    "absl/strings/internal/str_format/extension.cc",
    "absl/strings/internal/str_format/float_conversion.cc",
    "absl/strings/internal/str_format/output.cc",
    "absl/strings/internal/str_format/parser.cc",
    "absl/strings/internal/stringify_sink.cc",
    "absl/strings/internal/utf8.cc",
    "absl/strings/match.cc",
    "absl/strings/numbers.cc",
    "absl/strings/str_cat.cc",
    "absl/strings/string_view.cc",
    "absl/strings/str_replace.cc",
    "absl/strings/str_split.cc",
    "absl/strings/substitute.cc",
    "absl/synchronization/barrier.cc",
    "absl/synchronization/blocking_counter.cc",
    "absl/synchronization/internal/create_thread_identity.cc",
    "absl/synchronization/internal/futex_waiter.cc",
    "absl/synchronization/internal/graphcycles.cc",
    "absl/synchronization/internal/kernel_timeout.cc",
    "absl/synchronization/internal/per_thread_sem.cc",
    "absl/synchronization/internal/pthread_waiter.cc",
    "absl/synchronization/internal/sem_waiter.cc",
    "absl/synchronization/internal/stdcpp_waiter.cc",
    "absl/synchronization/internal/waiter_base.cc",
    "absl/synchronization/internal/win32_waiter.cc",
    "absl/synchronization/mutex.cc",
    "absl/synchronization/notification.cc",
    "absl/time/civil_time.cc",
    "absl/time/clock.cc",
    "absl/time/duration.cc",
    "absl/time/format.cc",
    "absl/time/internal/cctz/src/civil_time_detail.cc",
    "absl/time/internal/cctz/src/time_zone_fixed.cc",
    "absl/time/internal/cctz/src/time_zone_format.cc",
    "absl/time/internal/cctz/src/time_zone_if.cc",
    "absl/time/internal/cctz/src/time_zone_impl.cc",
    "absl/time/internal/cctz/src/time_zone_info.cc",
    "absl/time/internal/cctz/src/time_zone_libc.cc",
    "absl/time/internal/cctz/src/time_zone_lookup.cc",
    "absl/time/internal/cctz/src/time_zone_posix.cc",
    "absl/time/internal/cctz/src/zone_info_source.cc",
    "absl/time/time.cc",
};
pub const onnx_sources = [_][]const u8{
    "onnx/checker.cc",
    "onnx/common/assertions.cc",
    "onnx/common/interned_strings.cc",
    "onnx/common/ir_pb_converter.cc",
    "onnx/common/model_helpers.cc",
    "onnx/common/status.cc",
    "onnx/defs/attr_proto_util.cc",
    "onnx/defs/controlflow/defs.cc",
    "onnx/defs/controlflow/old.cc",
    "onnx/defs/controlflow/utils.cc",
    "onnx/defs/data_type_utils.cc",
    "onnx/defs/doc_strings.cc",
    "onnx/defs/function.cc",
    "onnx/defs/generator/defs.cc",
    "onnx/defs/generator/old.cc",
    "onnx/defs/generator/utils.cc",
    "onnx/defs/image/defs.cc",
    "onnx/defs/logical/defs.cc",
    "onnx/defs/logical/old.cc",
    "onnx/defs/math/defs.cc",
    "onnx/defs/math/old.cc",
    "onnx/defs/math/utils.cc",
    "onnx/defs/nn/defs.cc",
    "onnx/defs/nn/old.cc",
    "onnx/defs/nn/utils.cc",
    "onnx/defs/object_detection/defs.cc",
    "onnx/defs/object_detection/old.cc",
    "onnx/defs/optional/defs.cc",
    "onnx/defs/optional/old.cc",
    "onnx/defs/parser.cc",
    "onnx/defs/preview/defs.cc",
    "onnx/defs/printer.cc",
    "onnx/defs/quantization/defs.cc",
    "onnx/defs/quantization/old.cc",
    "onnx/defs/reduction/defs.cc",
    "onnx/defs/reduction/old.cc",
    "onnx/defs/reduction/utils.cc",
    "onnx/defs/rnn/defs.cc",
    "onnx/defs/rnn/old.cc",
    "onnx/defs/schema.cc",
    "onnx/defs/sequence/defs.cc",
    "onnx/defs/sequence/old.cc",
    "onnx/defs/sequence/utils.cc",
    "onnx/defs/shape_inference.cc",
    "onnx/defs/tensor/defs.cc",
    "onnx/defs/tensor/old.cc",
    "onnx/defs/tensor_proto_util.cc",
    "onnx/defs/tensor_util.cc",
    "onnx/defs/tensor/utils.cc",
    "onnx/defs/text/defs.cc",
    "onnx/defs/traditionalml/defs.cc",
    "onnx/defs/traditionalml/old.cc",
    "onnx/defs/training/defs.cc",
    "onnx/inliner/inliner.cc",
    "onnx/shape_inference/implementation.cc",
    "onnx/version_converter/convert.cc",
    "onnx/version_converter/helper.cc",
};
pub const re2_sources = [_][]const u8{
    "re2/bitmap256.cc",
    "re2/bitstate.cc",
    "re2/compile.cc",
    "re2/dfa.cc",
    "re2/filtered_re2.cc",
    "re2/mimics_pcre.cc",
    "re2/nfa.cc",
    "re2/onepass.cc",
    "re2/parse.cc",
    "re2/perl_groups.cc",
    "re2/prefilter.cc",
    "re2/prefilter_tree.cc",
    "re2/prog.cc",
    "re2/re2.cc",
    "re2/regexp.cc",
    "re2/set.cc",
    "re2/simplify.cc",
    "re2/tostring.cc",
    "re2/unicode_casefold.cc",
    "re2/unicode_groups.cc",
    "util/rune.cc",
    "util/strutil.cc",
};
const cpuinfo_sources = [_][]const u8{
    "src/api.c",
    "src/cache.c",
    "src/init.c",
    "src/log.c",
};

const cpuinfo_x86_sources = [_][]const u8{
    "src/x86/cache/descriptor.c",
    "src/x86/cache/deterministic.c",
    "src/x86/cache/init.c",
    "src/x86/info.c",
    "src/x86/init.c",
    "src/x86/isa.c",
    "src/x86/name.c",
    "src/x86/topology.c",
    "src/x86/uarch.c",
    "src/x86/vendor.c",
};

const cpuinfo_x86_linux_sources = [_][]const u8{
    "src/x86/linux/cpuinfo.c",
    "src/x86/linux/init.c",
};

const cpuinfo_x86_mach_sources = [_][]const u8{
    "src/x86/mach/init.c",
};

const cpuinfo_arm_sources = [_][]const u8{
    "src/arm/cache.c",
    "src/arm/uarch.c",
};

const cpuinfo_arm_linux_sources = [_][]const u8{
    "src/arm/linux/aarch64-isa.c",
    "src/arm/linux/chipset.c",
    "src/arm/linux/clusters.c",
    "src/arm/linux/cpuinfo.c",
    "src/arm/linux/hwcap.c",
    "src/arm/linux/init.c",
    "src/arm/linux/midr.c",
};

const cpuinfo_arm_mach_sources = [_][]const u8{
    "src/arm/mach/init.c",
};

const cpuinfo_mach_sources = [_][]const u8{
    "src/mach/topology.c",
};

const cpuinfo_linux_sources = [_][]const u8{
    "src/linux/cpulist.c",
    "src/linux/multiline.c",
    "src/linux/processors.c",
    "src/linux/smallfile.c",
};

const apple_device_discovery_sources = [_][]const u8{"core/platform/apple/device_discovery.cc"};
const linux_device_discovery_sources = [_][]const u8{"core/platform/linux/device_discovery.cc"};
const default_device_discovery_sources = [_][]const u8{"core/platform/device_discovery_default.cc"};

pub const ort_common_sources = [_][]const u8{
    "core/common/cpuid_info.cc",
    "core/common/cpuid_info_vendor.cc",
    "core/common/cpuid_uarch.cc",
    "core/common/denormal.cc",
    "core/common/helper.cc",
    "core/common/logging/capture.cc",
    "core/common/logging/logging.cc",
    "core/common/logging/sinks/ostream_sink.cc",
    "core/common/profiler.cc",
    "core/common/profiler_common.cc",
    "core/common/semver.cc",
    "core/common/status.cc",
    "core/common/threadpool.cc",
    "core/platform/check_intel.cc",
    "core/platform/device_discovery_common.cc",
    "core/platform/env.cc",
    "core/platform/env_time.cc",
    "core/platform/logging/make_platform_default_log_sink.cc",
    "core/platform/path_lib.cc",
    "core/platform/posix/env.cc",
    "core/platform/posix/env_time.cc",
    "core/platform/posix/stacktrace.cc",
    "core/platform/posix/telemetry_sha256.cc",
    "core/platform/telemetry.cc",
};

pub const ort_graph_sources = [_][]const u8{
    "core/graph/contrib_ops/attn_lstm_schema_defs.cc",
    "core/graph/contrib_ops/bert_defs.cc",
    "core/graph/contrib_ops/collective_defs.cc",
    "core/graph/contrib_ops/contrib_defs.cc",
    "core/graph/contrib_ops/diffusion_defs.cc",
    "core/graph/contrib_ops/internal_nhwc_onnx_schemas.cc",
    "core/graph/contrib_ops/nchwc_schema_defs.cc",
    "core/graph/contrib_ops/nhwc_schema_defs.cc",
    "core/graph/contrib_ops/onnx_deprecated_operators.cc",
    "core/graph/contrib_ops/onnx_function_util.cc",
    "core/graph/contrib_ops/quantization_defs.cc",
    "core/graph/contrib_ops/range_schema_defs.cc",
    "core/graph/contrib_ops/shape_inference_functions.cc",
    "core/graph/data_propagation/add_op_data_propagation.cc",
    "core/graph/data_propagation/custom_data_propagation.cc",
    "core/graph/data_propagation/div_op_data_propagation.cc",
    "core/graph/data_propagation/gather_op_data_propagation.cc",
    "core/graph/data_propagation/mul_op_data_propagation.cc",
    "core/graph/data_propagation/size_op_data_propagation.cc",
    "core/graph/data_propagation/squeeze_op_data_propagation.cc",
    "core/graph/data_propagation/sub_op_data_propagation.cc",
    "core/graph/data_propagation/unsqueeze_op_data_propagation.cc",
    "core/graph/ep_api_types.cc",
    "core/graph/function.cc",
    "core/graph/function_utils.cc",
    "core/graph/graph.cc",
    "core/graph/graph_flatbuffers_utils.cc",
    "core/graph/graph_proto_serializer.cc",
    "core/graph/graph_utils.cc",
    "core/graph/graph_viewer.cc",
    "core/graph/model.cc",
    "core/graph/model_helpers.cc",
    "core/graph/node_attr_utils.cc",
    "core/graph/op.cc",
    "core/graph/op_identifier_utils.cc",
    "core/graph/runtime_optimization_record_container.cc",
    "core/graph/schema_registry.cc",
};

pub const ort_framework_sources = [_][]const u8{
    "core/framework/allocation_planner.cc",
    "core/framework/allocator.cc",
    "core/framework/allocator_utils.cc",
    "core/framework/bfc_arena.cc",
    "core/framework/callback.cc",
    "core/framework/config_options.cc",
    "core/framework/copy.cc",
    "core/framework/customregistry.cc",
    "core/framework/data_transfer.cc",
    "core/framework/data_transfer_manager.cc",
    "core/framework/data_types.cc",
    "core/framework/debug_node_inputs_outputs_utils.cc",
    "core/framework/device_stream_collection.cc",
    "core/framework/empty.cc",
    "core/framework/endian_utils.cc",
    "core/framework/ep_context_options.cc",
    "core/framework/ep_context_utils.cc",
    "core/framework/error_code.cc",
    "core/framework/execution_frame.cc",
    "core/framework/execution_provider.cc",
    "core/framework/execution_steps.cc",
    "core/framework/ex_lib_loader.cc",
    "core/framework/external_data_loader.cc",
    "core/framework/external_data_loader_manager.cc",
    "core/framework/fallback_cpu_capability.cc",
    "core/framework/feeds_fetches_manager.cc",
    "core/framework/func_kernel.cc",
    "core/framework/fuse_nodes_funcs.cc",
    "core/framework/graph_partitioner.cc",
    "core/framework/kernel_def_builder.cc",
    "core/framework/kernel_registry.cc",
    "core/framework/kernel_registry_manager.cc",
    "core/framework/kernel_type_str_resolver.cc",
    "core/framework/kernel_type_str_resolver_utils.cc",
    "core/framework/layering_annotations.cc",
    "core/framework/library_handles.cc",
    "core/framework/max_shape_override.cc",
    "core/framework/memcpy.cc",
    "core/framework/memory_info.cc",
    "core/framework/mldata_type_utils.cc",
    "core/framework/model_metadef_id_generator.cc",
    "core/framework/murmurhash3.cc",
    "core/framework/node_index_info.cc",
    "core/framework/node_unit.cc",
    "core/framework/onnxruntime_map_type_info.cc",
    "core/framework/onnxruntime_optional_type_info.cc",
    "core/framework/onnxruntime_sequence_type_info.cc",
    "core/framework/onnxruntime_typeinfo.cc",
    "core/framework/op_kernel.cc",
    "core/framework/op_kernel_info.cc",
    "core/framework/op_node_proto_helper.cc",
    "core/framework/ort_value_pattern_planner.cc",
    "core/framework/ort_value_tensor_slicer.cc",
    "core/framework/partial_graph_execution_state.cc",
    "core/framework/plugin_data_transfer.cc",
    "core/framework/plugin_ep_stream.cc",
    "core/framework/prepacked_weights.cc",
    "core/framework/prepacked_weights_container.cc",
    "core/framework/random_generator.cc",
    "core/framework/random_seed.cc",
    "core/framework/resource_accountant.cc",
    "core/framework/run_options.cc",
    "core/framework/sequential_executor.cc",
    "core/framework/session_options.cc",
    "core/framework/session_state.cc",
    "core/framework/session_state_utils.cc",
    "core/framework/simple_tensor_allocator.cc",
    "core/framework/sparse_tensor.cc",
    "core/framework/sparse_utils.cc",
    "core/framework/stream_execution_context.cc",
    "core/framework/stream_handles.cc",
    "core/framework/tensor_allocator.cc",
    "core/framework/tensor.cc",
    "core/framework/tensor_external_data_info.cc",
    "core/framework/tensorprotoutils.cc",
    "core/framework/tensor_shape.cc",
    "core/framework/tensor_type_and_shape.cc",
    "core/framework/transpose_helper.cc",
    "core/framework/utils.cc",
};

pub const ort_optimizer_sources = [_][]const u8{
    "core/optimizer/attention_fusion.cc",
    "core/optimizer/bias_dropout_fusion.cc",
    "core/optimizer/bias_gelu_fusion.cc",
    "core/optimizer/bias_skip_layer_norm_fusion.cc",
    "core/optimizer/bias_softmax_fusion.cc",
    "core/optimizer/cast_chain_elimination.cc",
    "core/optimizer/cast_elimination.cc",
    "core/optimizer/common_subexpression_elimination.cc",
    "core/optimizer/compute_optimizer/shared_utils.cc",
    "core/optimizer/compute_optimizer/upstream_gather_actors.cc",
    "core/optimizer/compute_optimizer/upstream_gather.cc",
    "core/optimizer/compute_optimizer/upstream_reshape_actors.cc",
    "core/optimizer/compute_optimizer/upstream_reshape.cc",
    "core/optimizer/compute_optimizer/upstream_transformer_base.cc",
    "core/optimizer/concat_slice_elimination.cc",
    "core/optimizer/constant_folding.cc",
    "core/optimizer/constant_sharing.cc",
    "core/optimizer/conv_activation_fusion.cc",
    "core/optimizer/conv_add_act_fusion.cc",
    "core/optimizer/conv_add_fusion.cc",
    "core/optimizer/conv_bn_fusion.cc",
    "core/optimizer/conv_mul_fusion.cc",
    "core/optimizer/div_mul_fusion.cc",
    "core/optimizer/double_qdq_pairs_remover.cc",
    "core/optimizer/dq_matmulnbits_fusion.cc",
    "core/optimizer/dropout_elimination.cc",
    "core/optimizer/dynamic_quantize_matmul_fusion.cc",
    "core/optimizer/embed_layer_norm_fusion.cc",
    "core/optimizer/expand_elimination.cc",
    "core/optimizer/fast_gelu_fusion.cc",
    "core/optimizer/free_dim_override_transformer.cc",
    "core/optimizer/fuse_initializers_transformer.cc",
    "core/optimizer/gather_fusion.cc",
    "core/optimizer/gelu_approximation.cc",
    "core/optimizer/gelu_fusion.cc",
    "core/optimizer/gemm_activation_fusion.cc",
    "core/optimizer/gemm_sum_fusion.cc",
    "core/optimizer/gemm_transpose_fusion.cc",
    "core/optimizer/graph_optimizer_registry.cc",
    "core/optimizer/graph_transformer.cc",
    "core/optimizer/graph_transformer_mgr.cc",
    "core/optimizer/graph_transformer_utils.cc",
    "core/optimizer/group_query_attention_fusion.cc",
    "core/optimizer/group_query_attention_pre_norm_fusion.cc",
    "core/optimizer/identical_children_consolidation.cc",
    "core/optimizer/identity_elimination.cc",
    "core/optimizer/initializer.cc",
    "core/optimizer/insert_cast_transformer.cc",
    "core/optimizer/isinf_reducesum_fusion.cc",
    "core/optimizer/label_encoder_fusion.cc",
    "core/optimizer/layer_norm_fusion.cc",
    "core/optimizer/layout_transformation/layout_transformation.cc",
    "core/optimizer/matmul_activation_fusion.cc",
    "core/optimizer/matmul_add_fusion.cc",
    "core/optimizer/matmul_bn_fusion.cc",
    "core/optimizer/matmul_integer_to_float.cc",
    "core/optimizer/matmul_nbits_fusion.cc",
    "core/optimizer/matmul_nbits_mlp_fusion.cc",
    "core/optimizer/matmul_nbits_qkv_fusion.cc",
    "core/optimizer/matmul_scale_fusion.cc",
    "core/optimizer/matmul_transpose_fusion.cc",
    "core/optimizer/nchwc_transformer.cc",
    "core/optimizer/nhwc_transformer.cc",
    "core/optimizer/noop_elimination.cc",
    "core/optimizer/not_where_fusion.cc",
    "core/optimizer/optimizer_execution_frame.cc",
    "core/optimizer/pad_fusion.cc",
    "core/optimizer/pre_shape_node_elimination.cc",
    "core/optimizer/propagate_cast_ops.cc",
    "core/optimizer/qdq_transformer/avx2_weight_s8_to_u8.cc",
    "core/optimizer/qdq_transformer/clip_quantizelinear.cc",
    "core/optimizer/qdq_transformer/constant_folding_dq_node.cc",
    "core/optimizer/qdq_transformer/ensure_unique_dq_for_node_unit.cc",
    "core/optimizer/qdq_transformer/qdq_final_cleanup.cc",
    "core/optimizer/qdq_transformer/qdq_propagation.cc",
    "core/optimizer/qdq_transformer/qdq_s8_to_u8.cc",
    "core/optimizer/qdq_transformer/qdq_util.cc",
    "core/optimizer/qdq_transformer/relu_quantizelinear.cc",
    "core/optimizer/qdq_transformer/s8_to_u8.cc",
    "core/optimizer/qdq_transformer/selectors_actions/qdq_actions.cc",
    "core/optimizer/qdq_transformer/selectors_actions/qdq_selector_action_transformer.cc",
    "core/optimizer/qdq_transformer/selectors_actions/qdq_selectors.cc",
    "core/optimizer/qdq_transformer/selectors_actions/shared/utils.cc",
    "core/optimizer/qdq_transformer/weight_bias_quantization.cc",
    "core/optimizer/qdq_transformer/where_dummy_dq.cc",
    "core/optimizer/quick_gelu_fusion.cc",
    "core/optimizer/relu_clip_fusion.cc",
    "core/optimizer/reshape_fusion.cc",
    "core/optimizer/rule_based_graph_transformer.cc",
    "core/optimizer/selection_and_optimization_func.cc",
    "core/optimizer/selectors_actions/actions.cc",
    "core/optimizer/selectors_actions/helpers.cc",
    "core/optimizer/selectors_actions/selector_action_transformer.cc",
    "core/optimizer/skip_layer_norm_fusion.cc",
    "core/optimizer/slice_concat_to_space_to_depth_fusion.cc",
    "core/optimizer/slice_elimination.cc",
    "core/optimizer/stft_decomposition.cc",
    "core/optimizer/transformer_memcpy.cc",
    "core/optimizer/transpose_optimization/onnx_transpose_optimization.cc",
    "core/optimizer/transpose_optimization/ort_optimizer_api_impl.cc",
    "core/optimizer/transpose_optimization/ort_transpose_optimization.cc",
    "core/optimizer/transpose_optimizer.cc",
    "core/optimizer/unsqueeze_elimination.cc",
    "core/optimizer/utils.cc",
};

pub const ort_session_sources = [_][]const u8{
    "core/session/abi_ep_types.cc",
    "core/session/abi_session_options.cc",
    "core/session/allocator_adapters.cc",
    "core/session/compile_api.cc",
    "core/session/custom_ops.cc",
    "core/session/default_cpu_allocator_c_api.cc",
    "core/session/environment.cc",
    "core/session/experimental_c_api.cc",
    "core/session/inference_session.cc",
    "core/session/inference_session_utils.cc",
    "core/session/interop_api.cc",
    "core/session/IOBinding.cc",
    "core/session/lora_adapters.cc",
    "core/session/model_compilation_options.cc",
    "core/session/model_editor_c_api.cc",
    "core/session/model_package_api.cc",
    "core/session/model_package/model_package_context.cc",
    "core/session/model_package/model_package_options.cc",
    "core/session/model_package/model_package_variant_selector.cc",
    "core/session/onnxruntime_c_api.cc",
    "core/session/ort_env.cc",
    "core/session/plugin_ep/ep_api.cc",
    "core/session/plugin_ep/ep_control_flow_kernel_impls.cc",
    "core/session/plugin_ep/ep_event_profiling.cc",
    "core/session/plugin_ep/ep_factory_cpu.cc",
    "core/session/plugin_ep/ep_factory_dml.cc",
    "core/session/plugin_ep/ep_factory_internal.cc",
    "core/session/plugin_ep/ep_factory_internal_impl.cc",
    "core/session/plugin_ep/ep_factory_provider_bridge.cc",
    "core/session/plugin_ep/ep_factory_webgpu.cc",
    "core/session/plugin_ep/ep_kernel_registration.cc",
    "core/session/plugin_ep/ep_library_internal.cc",
    "core/session/plugin_ep/ep_library_plugin.cc",
    "core/session/plugin_ep/ep_library_provider_bridge.cc",
    "core/session/plugin_ep/ep_plugin_provider_interfaces.cc",
    "core/session/provider_bridge_ort.cc",
    "core/session/provider_policy_context.cc",
    "core/session/provider_registration.cc",
    "core/session/standalone_op_invoker.cc",
    "core/session/utils.cc",
};

pub const ort_util_sources = [_][]const u8{
    "core/util/math_cpu.cc",
    "core/util/thread_utils.cc",
};

pub const ort_lora_sources = [_][]const u8{
    "lora/adapter_format_utils.cc",
};

pub const ort_flatbuffers_sources = [_][]const u8{
    "core/flatbuffers/flatbuffers_utils.cc",
};

// The standalone model package library, which lives beside the runtime in the
// upstream tree and is linked into the session. Paths are relative to
// model_package/, not to onnxruntime/.
pub const model_package_sources = [_][]const u8{
    "src/asset_hasher.cc",
    "src/authoring.cc",
    "src/commit_prune_validate.cc",
    "src/manifest_parser.cc",
    "src/model_package_impl.cc",
    "src/path_resolver.cc",
    "src/sha256.cc",
};

pub const ort_providers_sources = [_][]const u8{
    "contrib_ops/cpu/activations.cc",
    "contrib_ops/cpu/attnlstm/attention_wrapper.cc",
    "contrib_ops/cpu/attnlstm/bahdanau_attention.cc",
    "contrib_ops/cpu/attnlstm/deep_cpu_attn_lstm.cc",
    "contrib_ops/cpu/attnlstm/uni_dir_attn_lstm.cc",
    "contrib_ops/cpu/bert/attention.cc",
    "contrib_ops/cpu/bert/attention_utils.cc",
    "contrib_ops/cpu/bert/bias_gelu.cc",
    "contrib_ops/cpu/bert/bifurcation_detector.cc",
    "contrib_ops/cpu/bert/causal_conv_with_state.cc",
    "contrib_ops/cpu/bert/decoder_masked_multihead_attention.cc",
    "contrib_ops/cpu/bert/embed_layer_norm.cc",
    "contrib_ops/cpu/bert/fast_gelu.cc",
    "contrib_ops/cpu/bert/group_query_attention.cc",
    "contrib_ops/cpu/bert/linear_attention.cc",
    "contrib_ops/cpu/bert/mrotary_embedding.cc",
    "contrib_ops/cpu/bert/multihead_attention.cc",
    "contrib_ops/cpu/bert/ngram_repeat_block.cc",
    "contrib_ops/cpu/bert/rotary_embedding.cc",
    "contrib_ops/cpu/cdist.cc",
    "contrib_ops/cpu/conv_transpose_with_dynamic_pads.cc",
    "contrib_ops/cpu/cpu_contrib_kernels.cc",
    "contrib_ops/cpu/crop_and_resize.cc",
    "contrib_ops/cpu/crop.cc",
    "contrib_ops/cpu/dynamicslice.cc",
    "contrib_ops/cpu/element_wise_ops.cc",
    "contrib_ops/cpu/expand_dims.cc",
    "contrib_ops/cpu/fused_activation.cc",
    "contrib_ops/cpu/fused_conv.cc",
    "contrib_ops/cpu/fused_gemm.cc",
    "contrib_ops/cpu/fused_matmul.cc",
    "contrib_ops/cpu/grid_sample.cc",
    "contrib_ops/cpu/image_scaler.cc",
    "contrib_ops/cpu/inverse.cc",
    "contrib_ops/cpu/layer_norm.cc",
    "contrib_ops/cpu/math/sparse_dense_matmul.cc",
    "contrib_ops/cpu/matmul_fpq4.cc",
    "contrib_ops/cpu/maxpool_with_mask.cc",
    "contrib_ops/cpu/mean_variance_normalization_exp.cc",
    "contrib_ops/cpu/moe/moe_cpu.cc",
    "contrib_ops/cpu/moe/moe_quantization_cpu.cc",
    "contrib_ops/cpu/moe/moe_utils.cc",
    "contrib_ops/cpu/murmur_hash3.cc",
    "contrib_ops/cpu/nchwc_ops.cc",
    "contrib_ops/cpu/quantization/attention_quant.cc",
    "contrib_ops/cpu/quantization/dynamic_quantize_lstm.cc",
    "contrib_ops/cpu/quantization/dynamic_quantize_matmul.cc",
    "contrib_ops/cpu/quantization/gather_block_quantized.cc",
    "contrib_ops/cpu/quantization/matmul_bnb4.cc",
    "contrib_ops/cpu/quantization/matmul_integer16.cc",
    "contrib_ops/cpu/quantization/matmul_nbits.cc",
    "contrib_ops/cpu/quantization/matmul_nbits_impl.cc",
    "contrib_ops/cpu/quantization/nhwc_max_pool.cc",
    "contrib_ops/cpu/quantization/qembed_layer_norm.cc",
    "contrib_ops/cpu/quantization/qlinear_activations.cc",
    "contrib_ops/cpu/quantization/qlinear_binary_op.cc",
    "contrib_ops/cpu/quantization/qlinear_concat.cc",
    "contrib_ops/cpu/quantization/qlinear_global_average_pool.cc",
    "contrib_ops/cpu/quantization/qlinear_lookup_table.cc",
    "contrib_ops/cpu/quantization/qlinear_pool.cc",
    "contrib_ops/cpu/quantization/qlinear_softmax.cc",
    "contrib_ops/cpu/quantization/qlinear_where.cc",
    "contrib_ops/cpu/quantization/quant_gemm.cc",
    "contrib_ops/cpu/sample.cc",
    "contrib_ops/cpu/skip_layer_norm.cc",
    "contrib_ops/cpu/sparse/sparse_attention.cc",
    "contrib_ops/cpu/tensor/dynamic_time_warping.cc",
    "contrib_ops/cpu/tensor/shrunken_gather.cc",
    "contrib_ops/cpu/tensor/unfold.cc",
    "contrib_ops/cpu/tokenizer.cc",
    "contrib_ops/cpu/transformers/beam_search.cc",
    "contrib_ops/cpu/transformers/beam_search_parameters.cc",
    "contrib_ops/cpu/transformers/beam_search_scorer.cc",
    "contrib_ops/cpu/transformers/generation_device_helper.cc",
    "contrib_ops/cpu/transformers/greedy_search.cc",
    "contrib_ops/cpu/transformers/greedy_search_parameters.cc",
    "contrib_ops/cpu/transformers/logits_processor.cc",
    "contrib_ops/cpu/transformers/sampling.cc",
    "contrib_ops/cpu/transformers/sampling_parameters.cc",
    "contrib_ops/cpu/transformers/sequences.cc",
    "contrib_ops/cpu/transformers/subgraph_base.cc",
    "contrib_ops/cpu/transformers/subgraph_gpt.cc",
    "contrib_ops/cpu/transformers/subgraph_t5_decoder.cc",
    "contrib_ops/cpu/transformers/subgraph_t5_encoder.cc",
    "contrib_ops/cpu/transformers/subgraph_whisper_decoder.cc",
    "contrib_ops/cpu/transformers/subgraph_whisper_encoder.cc",
    "contrib_ops/cpu/unique.cc",
    "contrib_ops/cpu/utils/dump_tensor.cc",
    "contrib_ops/cpu/word_conv_embedding.cc",
    "core/providers/cpu/activation/activations.cc",
    "core/providers/cpu/controlflow/if.cc",
    "core/providers/cpu/controlflow/loop.cc",
    "core/providers/cpu/controlflow/scan_8.cc",
    "core/providers/cpu/controlflow/scan_9.cc",
    "core/providers/cpu/controlflow/scan_utils.cc",
    "core/providers/cpu/controlflow/utils.cc",
    "core/providers/cpu/cpu_execution_provider.cc",
    "core/providers/cpu/cpu_provider_factory.cc",
    "core/providers/cpu/cpu_provider_shared.cc",
    "core/providers/cpu/fp16/fp16_conv.cc",
    "core/providers/cpu/fp16/fp16_pool.cc",
    "core/providers/cpu/generator/constant_of_shape.cc",
    "core/providers/cpu/generator/random.cc",
    "core/providers/cpu/generator/range.cc",
    "core/providers/cpu/llm/attention.cc",
    "core/providers/cpu/llm/rotary_embedding.cc",
    "core/providers/cpu/llm/tensorscatter.cc",
    "core/providers/cpu/math/clip.cc",
    "core/providers/cpu/math/cumprod.cc",
    "core/providers/cpu/math/cumsum.cc",
    "core/providers/cpu/math/det.cc",
    "core/providers/cpu/math/einsum.cc",
    "core/providers/cpu/math/einsum_utils/einsum_auxiliary_ops.cc",
    "core/providers/cpu/math/einsum_utils/einsum_compute_preprocessor.cc",
    "core/providers/cpu/math/einsum_utils/einsum_typed_compute_processor.cc",
    "core/providers/cpu/math/element_wise_ops.cc",
    "core/providers/cpu/math/gemm.cc",
    "core/providers/cpu/math/hardmax.cc",
    "core/providers/cpu/math/matmul.cc",
    "core/providers/cpu/math/round.cc",
    "core/providers/cpu/math/sign.cc",
    "core/providers/cpu/math/softmax.cc",
    "core/providers/cpu/math/softmax_shared.cc",
    "core/providers/cpu/math/top_k.cc",
    "core/providers/cpu/ml/array_feature_extractor.cc",
    "core/providers/cpu/ml/binarizer.cc",
    "core/providers/cpu/ml/cast_map.cc",
    "core/providers/cpu/ml/category_mapper.cc",
    "core/providers/cpu/ml/dictvectorizer.cc",
    "core/providers/cpu/ml/feature_vectorizer.cc",
    "core/providers/cpu/ml/imputer.cc",
    "core/providers/cpu/ml/label_encoder.cc",
    "core/providers/cpu/ml/linearclassifier.cc",
    "core/providers/cpu/ml/linearregressor.cc",
    "core/providers/cpu/ml/normalizer.cc",
    "core/providers/cpu/ml/onehotencoder.cc",
    "core/providers/cpu/ml/scaler.cc",
    "core/providers/cpu/ml/svmclassifier.cc",
    "core/providers/cpu/ml/svmregressor.cc",
    "core/providers/cpu/ml/tree_ensemble.cc",
    "core/providers/cpu/ml/tree_ensemble_classifier.cc",
    "core/providers/cpu/ml/tree_ensemble_helper.cc",
    "core/providers/cpu/ml/treeregressor.cc",
    "core/providers/cpu/ml/zipmap.cc",
    "core/providers/cpu/nn/batch_norm.cc",
    "core/providers/cpu/nn/conv.cc",
    "core/providers/cpu/nn/conv_transpose.cc",
    "core/providers/cpu/nn/deform_conv.cc",
    "core/providers/cpu/nn/dropout_op.cc",
    "core/providers/cpu/nn/flatten.cc",
    "core/providers/cpu/nn/instance_norm.cc",
    "core/providers/cpu/nn/layer_norm.cc",
    "core/providers/cpu/nn/layer_norm_impl.cc",
    "core/providers/cpu/nn/lp_norm.cc",
    "core/providers/cpu/nn/lrn.cc",
    "core/providers/cpu/nn/pool.cc",
    "core/providers/cpu/nn/rms_norm.cc",
    "core/providers/cpu/nn/roi_pool.cc",
    "core/providers/cpu/nn/shrink.cc",
    "core/providers/cpu/nn/tfidfvectorizer.cc",
    "core/providers/cpu/nn/Unpool.cc",
    "core/providers/cpu/object_detection/non_max_suppression.cc",
    "core/providers/cpu/object_detection/roialign.cc",
    "core/providers/cpu/optional/optional_ops.cc",
    "core/providers/cpu/quantization/conv_integer.cc",
    "core/providers/cpu/quantization/dynamicquantizelinear.cc",
    "core/providers/cpu/quantization/matmul_integer.cc",
    "core/providers/cpu/quantization/qlinearconv.cc",
    "core/providers/cpu/quantization/quantize_linear.cc",
    "core/providers/cpu/quantization/quantize_linear_matmul.cc",
    "core/providers/cpu/reduction/reduction_ops.cc",
    "core/providers/cpu/rnn/deep_cpu_gru.cc",
    "core/providers/cpu/rnn/deep_cpu_lstm.cc",
    "core/providers/cpu/rnn/lstm_base.cc",
    "core/providers/cpu/rnn/rnn.cc",
    "core/providers/cpu/rnn/rnn_helpers.cc",
    "core/providers/cpu/rnn/uni_directional_lstm.cc",
    "core/providers/cpu/sequence/concat_from_sequence.cc",
    "core/providers/cpu/sequence/sequence_ops.cc",
    "core/providers/cpu/signal/dft.cc",
    "core/providers/cpu/signal/window_functions.cc",
    "core/providers/cpu/tensor/affine_grid.cc",
    "core/providers/cpu/tensor/bitcast_op.cc",
    "core/providers/cpu/tensor/cast_op.cc",
    "core/providers/cpu/tensor/col2im.cc",
    "core/providers/cpu/tensor/compress.cc",
    "core/providers/cpu/tensor/concat.cc",
    "core/providers/cpu/tensor/expand.cc",
    "core/providers/cpu/tensor/eye_like.cc",
    "core/providers/cpu/tensor/gather.cc",
    "core/providers/cpu/tensor/gather_elements.cc",
    "core/providers/cpu/tensor/gather_nd.cc",
    "core/providers/cpu/tensor/gelu.cc",
    "core/providers/cpu/tensor/grid_sample.cc",
    "core/providers/cpu/tensor/identity_op.cc",
    "core/providers/cpu/tensor/isinf.cc",
    "core/providers/cpu/tensor/isnan.cc",
    "core/providers/cpu/tensor/mean_variance_normalization.cc",
    "core/providers/cpu/tensor/nonzero_op.cc",
    "core/providers/cpu/tensor/onehot.cc",
    "core/providers/cpu/tensor/pad.cc",
    "core/providers/cpu/tensor/reshape.cc",
    "core/providers/cpu/tensor/resize.cc",
    "core/providers/cpu/tensor/reverse_sequence.cc",
    "core/providers/cpu/tensor/scatter.cc",
    "core/providers/cpu/tensor/scatter_nd.cc",
    "core/providers/cpu/tensor/shape_op.cc",
    "core/providers/cpu/tensor/size.cc",
    "core/providers/cpu/tensor/slice.cc",
    "core/providers/cpu/tensor/space_depth_ops.cc",
    "core/providers/cpu/tensor/split.cc",
    "core/providers/cpu/tensor/squeeze.cc",
    "core/providers/cpu/tensor/tile.cc",
    "core/providers/cpu/tensor/transpose.cc",
    "core/providers/cpu/tensor/trilu.cc",
    "core/providers/cpu/tensor/unique.cc",
    "core/providers/cpu/tensor/unsqueeze.cc",
    "core/providers/cpu/tensor/upsample.cc",
    "core/providers/cpu/tensor/where_op.cc",
    "core/providers/cpu/text/regex_full_match.cc",
    "core/providers/cpu/text/string_concat.cc",
    "core/providers/cpu/text/string_normalizer.cc",
    "core/providers/cpu/text/string_split.cc",
    "core/providers/execution_provider_factory.cc",
    "core/providers/get_execution_providers.cc",
    "core/providers/partitioning_utils.cc",
    "core/providers/utils.cc",
};

pub const ort_mlas_sources = [_][]const u8{
    "core/mlas/lib/activate.cpp",
    "core/mlas/lib/cast.cpp",
    "core/mlas/lib/compute.cpp",
    "core/mlas/lib/convolve.cpp",
    "core/mlas/lib/convsym.cpp",
    "core/mlas/lib/dequantize.cpp",
    "core/mlas/lib/eltwise.cpp",
    "core/mlas/lib/erf.cpp",
    "core/mlas/lib/flashattn.cpp",
    "core/mlas/lib/flashattn_gqa.cpp",
    "core/mlas/lib/flashattn_qkv.cpp",
    "core/mlas/lib/gelu.cpp",
    "core/mlas/lib/halfconv.cpp",
    "core/mlas/lib/halfgemm.cpp",
    "core/mlas/lib/layernorm.cpp",
    "core/mlas/lib/logistic.cpp",
    "core/mlas/lib/platform.cpp",
    "core/mlas/lib/pooling.cpp",
    "core/mlas/lib/q4_dq.cpp",
    "core/mlas/lib/q4gemm.cpp",
    "core/mlas/lib/qdwconv.cpp",
    "core/mlas/lib/qdwconv_kernelsize.cpp",
    "core/mlas/lib/qgemm.cpp",
    "core/mlas/lib/qgemm_kernel_default.cpp",
    "core/mlas/lib/qkv_quant.cpp",
    "core/mlas/lib/qladd.cpp",
    "core/mlas/lib/qlgavgpool.cpp",
    "core/mlas/lib/qlmul.cpp",
    "core/mlas/lib/qlutgemm.cpp",
    "core/mlas/lib/qnbitgemm.cpp",
    "core/mlas/lib/qpostprocessor.cpp",
    "core/mlas/lib/quantize.cpp",
    "core/mlas/lib/reorder.cpp",
    "core/mlas/lib/rotary_embedding.cpp",
    "core/mlas/lib/saturation_check.cpp",
    "core/mlas/lib/sconv_nchw_depthwise_multiplier_greater_than_1.cpp",
    "core/mlas/lib/sgemm.cpp",
    "core/mlas/lib/silu.cpp",
    "core/mlas/lib/snchwc.cpp",
    "core/mlas/lib/sqnbitgemm_kernel_avx512_2bit.cpp",
    "core/mlas/lib/tanh.cpp",
    "core/mlas/lib/threading.cpp",
    "core/mlas/lib/transpose.cpp",
};

const ort_mlas_x86_64_sources = [_][]const u8{
    "core/mlas/lib/activate_fp16.cpp",
    "core/mlas/lib/dgemm.cpp",
    "core/mlas/lib/dwconv.cpp",
    "core/mlas/lib/pooling_fp16.cpp",
    "core/mlas/lib/qgemm_kernel_avx2.cpp",
    "core/mlas/lib/x86_64/QgemmU8S8KernelAmxCommon.S",
};

const ort_mlas_aarch64_sources = [_][]const u8{
    "core/mlas/lib/aarch64/ConvSymS8KernelDot.S",
    "core/mlas/lib/aarch64/ConvSymS8KernelDotLd64.S",
    "core/mlas/lib/aarch64/ConvSymS8KernelNeon.S",
    "core/mlas/lib/aarch64/ConvSymU8KernelDot.S",
    "core/mlas/lib/aarch64/ConvSymU8KernelNeon.S",
    "core/mlas/lib/aarch64/DepthwiseQConvKernelSize9Neon.S",
    "core/mlas/lib/aarch64/DepthwiseQConvSymS8KernelNeon.S",
    "core/mlas/lib/aarch64/DepthwiseQConvSymU8KernelNeon.S",
    "core/mlas/lib/aarch64/QgemmS8S8KernelNeon.S",
    "core/mlas/lib/aarch64/QgemmS8S8KernelSdot.S",
    "core/mlas/lib/aarch64/QgemmU8X8KernelNeon.S",
    "core/mlas/lib/aarch64/QgemmU8X8KernelUdot.S",
    "core/mlas/lib/aarch64/SgemmKernelNeon.S",
    "core/mlas/lib/aarch64/SgemvKernelNeon.S",
    "core/mlas/lib/aarch64/SymQgemmS8KernelNeon.S",
    "core/mlas/lib/aarch64/SymQgemmS8KernelSdot.S",
    "core/mlas/lib/aarch64/SymQgemmS8KernelSdotLd64.S",
    "core/mlas/lib/eltwise_kernel_neon.cpp",
    "core/mlas/lib/hgemm_kernel_neon.cpp",
    "core/mlas/lib/qgemm_kernel_neon.cpp",
    "core/mlas/lib/qgemm_kernel_sdot.cpp",
    "core/mlas/lib/qgemm_kernel_udot.cpp",
    "core/mlas/lib/qkv_quant_kernel_neon.cpp",
    "core/mlas/lib/qnbitgemm_kernel_neon.cpp",
    "core/mlas/lib/rotary_embedding_kernel_neon.cpp",
    "core/mlas/lib/sconv_nchw_depthwise_multiplier_1.cpp",
    "core/mlas/lib/softmax_kernel_neon.cpp",
    "core/mlas/lib/sqnbitgemm_kernel_neon_fp32.cpp",
};

/// Lowers an architecture's own feature enum to the untyped set `MlasGroup`
/// carries, so that groups for either architecture share the one type.
fn featureSet(comptime Feature: type, comptime features: []const Feature) std.Target.Cpu.Feature.Set {
    comptime {
        var set: std.Target.Cpu.Feature.Set = .empty;
        for (features) |feature| set.addFeature(@intFromEnum(feature));
        return set;
    }
}

fn x86(comptime features: []const std.Target.x86.Feature) std.Target.Cpu.Feature.Set {
    return featureSet(std.Target.x86.Feature, features);
}

fn arm(comptime features: []const std.Target.aarch64.Feature) std.Target.Cpu.Feature.Set {
    return featureSet(std.Target.aarch64.Feature, features);
}

pub const MlasGroup = struct {
    /// The ISA baseline these files are compiled against, on top of the
    /// target's own.
    features: std.Target.Cpu.Feature.Set,
    files: []const []const u8,
    flags: []const []const u8 = &.{},
};

const ort_mlas_x86_64_groups = [_]MlasGroup{
    .{
        .features = x86(&.{.avx}),
        .files = &.{
            "core/mlas/lib/intrinsics/avx/min_max_elements.cpp",
            "core/mlas/lib/x86_64/DgemmKernelAvx.S",
            "core/mlas/lib/x86_64/SconvKernelAvx.S",
            "core/mlas/lib/x86_64/SgemmKernelAvx.S",
            "core/mlas/lib/x86_64/SgemmKernelM1Avx.S",
            "core/mlas/lib/x86_64/SgemmKernelM1TransposeBAvx.S",
            "core/mlas/lib/x86_64/SgemmTransposePackB16x4Avx.S",
            "core/mlas/lib/x86_64/SoftmaxKernelAvx.S",
            "core/mlas/lib/x86_64/SpoolKernelAvx.S",
        },
    },
    .{
        .features = x86(&.{ .avx2, .avx512bw, .avx512dq, .avx512f, .avx512vl }),
        .files = &.{
            "core/mlas/lib/qgemm_kernel_amx.cpp",
            "core/mlas/lib/x86_64/QgemmU8S8KernelAmx.S",
        },
    },
    .{
        .features = x86(&.{ .avx2, .f16c, .fma }),
        .files = &.{
            "core/mlas/lib/intrinsics/avx2/qdwconv_avx2.cpp",
            "core/mlas/lib/intrinsics/avx2/qladd_avx2.cpp",
            "core/mlas/lib/intrinsics/avx2/saturation_check_avx2.cpp",
            "core/mlas/lib/qkv_quant_kernel_avx2.cpp",
            "core/mlas/lib/rotary_embedding_kernel_avx2.cpp",
            "core/mlas/lib/sqnbitgemm_kernel_avx2.cpp",
            "core/mlas/lib/sqnbitgemm_lut_kernel_avx2.cpp",
            "core/mlas/lib/x86_64/ConvSymKernelAvx2.S",
            "core/mlas/lib/x86_64/cvtfp16Avx.S",
            "core/mlas/lib/x86_64/DgemmKernelFma3.S",
            "core/mlas/lib/x86_64/ErfKernelFma3.S",
            "core/mlas/lib/x86_64/LogisticKernelFma3.S",
            "core/mlas/lib/x86_64/QgemmU8S8KernelAvx2.S",
            "core/mlas/lib/x86_64/QgemmU8U8KernelAvx2.S",
            "core/mlas/lib/x86_64/QgemmU8X8KernelAvx2.S",
            "core/mlas/lib/x86_64/QgemvU8S8KernelAvx2.S",
            "core/mlas/lib/x86_64/QgemvU8S8KernelAvxVnni.S",
            "core/mlas/lib/x86_64/SconvKernelFma3.S",
            "core/mlas/lib/x86_64/SgemmKernelFma3.S",
            "core/mlas/lib/x86_64/TanhKernelFma3.S",
            "core/mlas/lib/x86_64/TransKernelFma3.S",
        },
    },
    .{
        // The 2-bit dequant kernel keeps its multiply and add apart to stay
        // bit-identical to the scalar kernel, so contraction is turned off.
        .features = x86(&.{ .avx2, .f16c, .fma }),
        .files = &.{
            "core/mlas/lib/intrinsics/avx2/q2_dq_avx2.cpp",
        },
        .flags = &.{"-ffp-contract=off"},
    },
    .{
        // AVX-VNNI lives in a translation unit of its own so the vectorizer
        // cannot slip a VNNI instruction into the plain AVX2 kernels.
        .features = x86(&.{ .avx2, .avxvnni, .f16c, .fma }),
        .files = &.{
            "core/mlas/lib/sqnbitgemm_kernel_avx2vnni.cpp",
        },
    },
    .{
        .features = x86(&.{.avx512f}),
        .files = &.{
            "core/mlas/lib/intrinsics/avx512/gelu_avx512f.cpp",
            "core/mlas/lib/intrinsics/avx512/quantize_avx512f.cpp",
            "core/mlas/lib/intrinsics/avx512/sconv_nchw_depthwise_multiplier_greater_than_1_avx512f.cpp",
            "core/mlas/lib/intrinsics/avx512/silu_avx512f.cpp",
            "core/mlas/lib/x86_64/DgemmKernelAvx512F.S",
            "core/mlas/lib/x86_64/SconvKernelAvx512F.S",
            "core/mlas/lib/x86_64/SgemmKernelAvx512F.S",
            "core/mlas/lib/x86_64/SoftmaxKernelAvx512F.S",
            "core/mlas/lib/x86_64/SpoolKernelAvx512F.S",
            "core/mlas/lib/x86_64/TransKernelAvx512F.S",
        },
    },
    .{
        .features = x86(&.{ .avx512bw, .avx512dq, .avx512vl, .avx512vnni, .fma }),
        .files = &.{
            "core/mlas/lib/sqnbitgemm_kernel_avx512.cpp",
            "core/mlas/lib/x86_64/ConvSymKernelAvx512Core.S",
            "core/mlas/lib/x86_64/QgemmU8X8KernelAvx512Core.S",
            "core/mlas/lib/x86_64/QgemvU8S8KernelAvx512Core.S",
            "core/mlas/lib/x86_64/QgemvU8S8KernelAvx512Vnni.S",
        },
    },
    .{
        .features = x86(&.{ .avx512bw, .avx512dq, .avx512f, .avx512vl, .avx512vnni, .f16c, .fma }),
        .files = &.{
            "core/mlas/lib/q4gemm_avx512.cpp",
            "core/mlas/lib/qkv_quant_kernel_avx512vnni.cpp",
            "core/mlas/lib/sqnbitgemm_kernel_avx512vnni.cpp",
            "core/mlas/lib/sqnbitgemm_kernel_avx512vnni_2bit.cpp",
        },
    },
    .{
        .features = x86(&.{.sse2}),
        .files = &.{
            "core/mlas/lib/qgemm_kernel_sse.cpp",
            "core/mlas/lib/x86_64/cvtfp16a.S",
            "core/mlas/lib/x86_64/DgemmKernelSse2.S",
            "core/mlas/lib/x86_64/SconvKernelSse2.S",
            "core/mlas/lib/x86_64/SgemmKernelSse2.S",
            "core/mlas/lib/x86_64/SgemmTransposePackB16x4Sse2.S",
            "core/mlas/lib/x86_64/SpoolKernelSse2.S",
        },
    },
};

const ort_mlas_aarch64_groups = [_]MlasGroup{
    .{
        // All three reach for fp16 NEON arithmetic unconditionally, which a
        // plain v8-a baseline does not assemble -- upstream compiles exactly
        // these with -march=armv8.2-a+fp16. The kernels stay behind
        // MlasFp16AccelerationSupported, so a machine without fp16 never
        // reaches them.
        .features = arm(&.{.fullfp16}),
        .files = &.{
            "core/mlas/lib/activate_fp16.cpp",
            "core/mlas/lib/dwconv.cpp",
            "core/mlas/lib/pooling_fp16.cpp",
        },
    },
    .{
        .features = arm(&.{.dotprod}),
        .files = &.{
            "core/mlas/lib/sqnbitgemm_kernel_neon_int8.cpp",
            "core/mlas/lib/sqnbitgemm_kernel_neon_int8_2bit.cpp",
        },
    },
    .{
        .features = arm(&.{.i8mm}),
        .files = &.{
            "core/mlas/lib/sqnbitgemm_kernel_neon_int8_i8mm.cpp",
        },
    },
};

// The OpenVINO execution provider, ORT's only route to an Intel NPU. These
// go into a shared library of their own rather than into libonnxruntime.a:
// ORT reaches an OpenVINO EP by dlopening it and calling CreateEpFactories,
// and the .so in turn calls back into the runtime through the one symbol
// Provider_GetHost. See `openvinoProvider` in build.zig.
pub const ort_openvino_sources = [_][]const u8{
    "core/providers/openvino/backend_manager.cc",
    "core/providers/openvino/backend_utils.cc",
    "core/providers/openvino/backends/backend_factory.cc",
    "core/providers/openvino/backends/basic_backend.cc",
    "core/providers/openvino/onnx_ctx_model_helper.cc",
    "core/providers/openvino/openvino_execution_provider.cc",
    "core/providers/openvino/openvino_parser_utils.cc",
    "core/providers/openvino/openvino_provider_dllmain.cc",
    "core/providers/openvino/openvino_provider_factory.cc",
    "core/providers/openvino/ov_allocator.cc",
    "core/providers/openvino/ov_bin_manager.cc",
    "core/providers/openvino/ov_factory.cc",
    "core/providers/openvino/ov_interface.cc",
    "core/providers/openvino/ov_protobuf_utils.cpp",
    "core/providers/openvino/ov_shared_context.cc",
    "core/providers/openvino/ov_stateful_patch_utils.cc",
    "core/providers/openvino/ov_tracing.cc",
    "core/providers/openvino/ov_versions/capability.cc",
    "core/providers/openvino/ov_versions/data_ops.cc",
    "core/providers/openvino/ov_versions/utils.cc",
    "core/providers/openvino/qdq_transformations/qdq_scales_fix.cc",
    "core/providers/openvino/qdq_transformations/qdq_stripping.cc",
};

// The provider side of the bridge: re-implements the runtime's internal C++
// types (Node, GraphViewer, Tensor, ...) as forwarders onto the ProviderHost
// vtable that Provider_GetHost hands back. Compiled into every provider .so,
// never into the runtime itself.
pub const ort_provider_shared_sources = [_][]const u8{
    "core/providers/shared_library/provider_bridge_provider.cc",
    "core/providers/shared_library/provider_ort_api_init.cc",
};

// The mailbox the two halves of the bridge meet in: one global ProviderHost
// pointer, a setter and a getter. Upstream builds it as its own tiny shared
// library, and so does build.zig, because that is what makes the pointer a
// single object -- the runtime dlopens it and calls Provider_SetHost, every
// provider .so links it and calls Provider_GetHost.
pub const ort_provider_host_sources = [_][]const u8{
    "core/providers/shared/common.cc",
};

/// The CUDA execution provider's host half: kernel registration, the provider
/// itself, and everything that is ordinary C++ rather than device code.
///
/// Both operator trees, `core/providers/cuda` and `contrib_ops/cuda`. The
/// com.microsoft kernels are not optional in practice: ORT's own level-2
/// optimiser rewrites subgraphs into contrib operators when it sees a CUDA EP
/// -- an activation becomes com.microsoft.Gelu -- and then fails to load the
/// graph if the provider has no kernel to match.
///
/// Left out, following upstream's CMake for a build below SM90 with FP4/FP8
/// quantised-MoE, ATen, NCCL and the TensorRT fused attention off: the
/// precompiled-header pair, the experimental plugin-EP variant, the ATen and
/// NCCL collective operators, the FP4/FP8 MoE GEMM kernels, and the 99 prebuilt
/// TensorRT fused multi-head attention cubin blobs.
pub const ort_cuda_sources = [_][]const u8{
    "contrib_ops/cuda/activation/activations.cc",
    "contrib_ops/cuda/bert/attention.cc",
    "contrib_ops/cuda/bert/attention_kernel_options.cc",
    "contrib_ops/cuda/bert/causal_conv_with_state.cc",
    "contrib_ops/cuda/bert/cudnn_fmha/cudnn_flash_attention.cc",
    "contrib_ops/cuda/bert/decoder_attention.cc",
    "contrib_ops/cuda/bert/decoder_masked_multihead_attention.cc",
    "contrib_ops/cuda/bert/decoder_masked_self_attention.cc",
    "contrib_ops/cuda/bert/embed_layer_norm.cc",
    "contrib_ops/cuda/bert/fast_gelu.cc",
    "contrib_ops/cuda/bert/flash_attention/flash_api.cc",
    "contrib_ops/cuda/bert/gated_add.cc",
    "contrib_ops/cuda/bert/gemma_rotary_emb.cc",
    "contrib_ops/cuda/bert/group_query_attention.cc",
    "contrib_ops/cuda/bert/lean_attention/lean_api.cc",
    "contrib_ops/cuda/bert/linear_attention.cc",
    "contrib_ops/cuda/bert/linear_attention_gates.cc",
    "contrib_ops/cuda/bert/longformer_attention.cc",
    "contrib_ops/cuda/bert/mrotary_embedding.cc",
    "contrib_ops/cuda/bert/multihead_attention.cc",
    "contrib_ops/cuda/bert/ngram_repeat_block.cc",
    "contrib_ops/cuda/bert/packed_attention.cc",
    "contrib_ops/cuda/bert/packed_multihead_attention.cc",
    "contrib_ops/cuda/bert/paged_attention.cc",
    "contrib_ops/cuda/bert/relative_attn_bias.cc",
    "contrib_ops/cuda/bert/remove_padding.cc",
    "contrib_ops/cuda/bert/restore_padding.cc",
    "contrib_ops/cuda/bert/rotary_embedding.cc",
    "contrib_ops/cuda/bert/skip_layer_norm.cc",
    "contrib_ops/cuda/bert/tensorrt_fused_multihead_attention/cudaDriverWrapper.cc",
    "contrib_ops/cuda/bert/transformer_common.cc",
    "contrib_ops/cuda/conv_transpose_with_dynamic_pads.cc",
    "contrib_ops/cuda/cuda_contrib_kernels.cc",
    "contrib_ops/cuda/diffusion/bias_add.cc",
    "contrib_ops/cuda/diffusion/bias_split_gelu.cc",
    "contrib_ops/cuda/diffusion/group_norm.cc",
    "contrib_ops/cuda/diffusion/group_norm_common_base.cc",
    "contrib_ops/cuda/diffusion/nhwc_conv.cc",
    "contrib_ops/cuda/fused_conv.cc",
    "contrib_ops/cuda/inverse.cc",
    "contrib_ops/cuda/layer_norm.cc",
    "contrib_ops/cuda/llm/cutlass_heuristic.cc",
    "contrib_ops/cuda/llm/fpA_intB_gemm_profiler.cc",
    "contrib_ops/cuda/llm/gemm_profiler.cc",
    "contrib_ops/cuda/llm/moe_gemm/moe_gemm_profiler.cc",
    "contrib_ops/cuda/math/bias_dropout.cc",
    "contrib_ops/cuda/math/bias_gelu.cc",
    "contrib_ops/cuda/math/bias_softmax.cc",
    "contrib_ops/cuda/math/bitmask_dropout.cc",
    "contrib_ops/cuda/math/complex_mul.cc",
    "contrib_ops/cuda/math/fft_ops.cc",
    "contrib_ops/cuda/math/fused_matmul.cc",
    "contrib_ops/cuda/math/gemm_float8.cc",
    "contrib_ops/cuda/math/isfinite.cc",
    "contrib_ops/cuda/math/matmul_block_scaled_fp4.cc",
    "contrib_ops/cuda/math/matmul_block_scaled_fp8.cc",
    "contrib_ops/cuda/moe/moe.cc",
    "contrib_ops/cuda/moe/moe_quantization.cc",
    "contrib_ops/cuda/quantization/attention_quantization.cc",
    "contrib_ops/cuda/quantization/gather_block_quantized.cc",
    "contrib_ops/cuda/quantization/matmul_bnb4.cc",
    "contrib_ops/cuda/quantization/matmul_nbits.cc",
    "contrib_ops/cuda/quantization/qordered_ops/qordered_attention.cc",
    "contrib_ops/cuda/quantization/qordered_ops/qordered_layer_norm.cc",
    "contrib_ops/cuda/quantization/qordered_ops/qordered_longformer_attention.cc",
    "contrib_ops/cuda/quantization/qordered_ops/qordered_matmul.cc",
    "contrib_ops/cuda/quantization/qordered_ops/qordered_matmul_utils.cc",
    "contrib_ops/cuda/quantization/qordered_ops/qordered_qdq.cc",
    "contrib_ops/cuda/quantization/qordered_ops/qordered_unary_ops.cc",
    "contrib_ops/cuda/quantization/quantize_dequantize_linear.cc",
    "contrib_ops/cuda/sparse/sparse_attention.cc",
    "contrib_ops/cuda/sparse/sparse_attention_v1/sparse_attention_v1_api.cc",
    "contrib_ops/cuda/sparse/sparse_attention_v1/sparse_attention_v1_bf16_d128_n64_e0_sm80.cc",
    "contrib_ops/cuda/sparse/sparse_attention_v1/sparse_attention_v1_bf16_d128_n64_e0_sm90.cc",
    "contrib_ops/cuda/sparse/sparse_attention_v1/sparse_attention_v1_bf16_d128_n64_e1_sm80.cc",
    "contrib_ops/cuda/sparse/sparse_attention_v1/sparse_attention_v1_bf16_d128_n64_e1_sm90.cc",
    "contrib_ops/cuda/sparse/sparse_attention_v1/sparse_attention_v1_fp16_d128_n64_e0_sm75.cc",
    "contrib_ops/cuda/sparse/sparse_attention_v1/sparse_attention_v1_fp16_d128_n64_e0_sm80.cc",
    "contrib_ops/cuda/sparse/sparse_attention_v1/sparse_attention_v1_fp16_d128_n64_e0_sm90.cc",
    "contrib_ops/cuda/sparse/sparse_attention_v1/sparse_attention_v1_fp16_d128_n64_e1_sm75.cc",
    "contrib_ops/cuda/sparse/sparse_attention_v1/sparse_attention_v1_fp16_d128_n64_e1_sm80.cc",
    "contrib_ops/cuda/sparse/sparse_attention_v1/sparse_attention_v1_fp16_d128_n64_e1_sm90.cc",
    "contrib_ops/cuda/sparse/sparse_attention_v2/sparse_attention_v2_api.cc",
    "contrib_ops/cuda/sparse/sparse_attention_v2/sparse_attention_v2_bf16_d128_m64_16_n64_b1_sm80.cc",
    "contrib_ops/cuda/sparse/sparse_attention_v2/sparse_attention_v2_bf16_d128_m64_16_n64_b1_sm90.cc",
    "contrib_ops/cuda/sparse/sparse_attention_v2/sparse_attention_v2_bf16_d128_m64_64_n64_b1_sm80.cc",
    "contrib_ops/cuda/sparse/sparse_attention_v2/sparse_attention_v2_bf16_d128_m64_64_n64_b1_sm90.cc",
    "contrib_ops/cuda/sparse/sparse_attention_v2/sparse_attention_v2_fp16_d128_m64_16_n64_b1_sm75.cc",
    "contrib_ops/cuda/sparse/sparse_attention_v2/sparse_attention_v2_fp16_d128_m64_16_n64_b1_sm80.cc",
    "contrib_ops/cuda/sparse/sparse_attention_v2/sparse_attention_v2_fp16_d128_m64_16_n64_b1_sm90.cc",
    "contrib_ops/cuda/sparse/sparse_attention_v2/sparse_attention_v2_fp16_d128_m64_64_n64_b1_sm75.cc",
    "contrib_ops/cuda/sparse/sparse_attention_v2/sparse_attention_v2_fp16_d128_m64_64_n64_b1_sm80.cc",
    "contrib_ops/cuda/sparse/sparse_attention_v2/sparse_attention_v2_fp16_d128_m64_64_n64_b1_sm90.cc",
    "contrib_ops/cuda/tensor/crop.cc",
    "contrib_ops/cuda/tensor/dynamicslice.cc",
    "contrib_ops/cuda/tensor/dynamic_time_warping.cc",
    "contrib_ops/cuda/tensor/image_scaler.cc",
    "contrib_ops/cuda/tensor/shrunken_gather.cc",
    "contrib_ops/cuda/tensor/trilu.cc",
    "contrib_ops/cuda/tensor/unfold.cc",
    "contrib_ops/cuda/transformers/beam_search.cc",
    "contrib_ops/cuda/transformers/generation_device_helper.cc",
    "contrib_ops/cuda/transformers/greedy_search.cc",
    "contrib_ops/cuda/transformers/sampling.cc",
    "contrib_ops/cuda/utils/dump_cuda_tensor.cc",
    "core/providers/cuda/activation/activations.cc",
    "core/providers/cuda/controlflow/if.cc",
    "core/providers/cuda/controlflow/loop.cc",
    "core/providers/cuda/controlflow/scan.cc",
    "core/providers/cuda/cuda_allocator.cc",
    "core/providers/cuda/cuda_call.cc",
    "core/providers/cuda/cuda_check_memory.cc",
    "core/providers/cuda/cuda_common.cc",
    "core/providers/cuda/cuda_execution_provider.cc",
    "core/providers/cuda/cuda_execution_provider_info.cc",
    "core/providers/cuda/cuda_graph.cc",
    "core/providers/cuda/cuda_mempool_arena.cc",
    "core/providers/cuda/cuda_nhwc_kernels.cc",
    "core/providers/cuda/cuda_profiler.cc",
    "core/providers/cuda/cuda_provider_factory.cc",
    "core/providers/cuda/cuda_provider_interface.cc",
    "core/providers/cuda/cuda_stream_handle.cc",
    "core/providers/cuda/cudnn_common.cc",
    "core/providers/cuda/cudnn_fe_call.cc",
    "core/providers/cuda/cudnn_loader.cc",
    "core/providers/cuda/cudnn_stub.cc",
    "core/providers/cuda/cufft_loader.cc",
    "core/providers/cuda/cufft_stub.cc",
    "core/providers/cuda/cupti_manager.cc",
    "core/providers/cuda/generator/constant_of_shape.cc",
    "core/providers/cuda/generator/random.cc",
    "core/providers/cuda/generator/range.cc",
    "core/providers/cuda/gpu_data_transfer.cc",
    "core/providers/cuda/integer_gemm.cc",
    "core/providers/cuda/llm/attention.cc",
    "core/providers/cuda/llm/rotary_embedding.cc",
    "core/providers/cuda/llm/tensorscatter.cc",
    "core/providers/cuda/math/binary_elementwise_ops.cc",
    "core/providers/cuda/math/clip.cc",
    "core/providers/cuda/math/cumsum.cc",
    "core/providers/cuda/math/einsum.cc",
    "core/providers/cuda/math/einsum_utils/einsum_auxiliary_ops.cc",
    "core/providers/cuda/math/gemm.cc",
    "core/providers/cuda/math/matmul.cc",
    "core/providers/cuda/math/matmul_integer.cc",
    "core/providers/cuda/math/softmax.cc",
    "core/providers/cuda/math/softmax_common.cc",
    "core/providers/cuda/math/topk.cc",
    "core/providers/cuda/math/unary_elementwise_ops.cc",
    "core/providers/cuda/math/variadic_elementwise_ops.cc",
    "core/providers/cuda/ml/label_encoder.cc",
    "core/providers/cuda/nn/batch_norm.cc",
    "core/providers/cuda/nn/conv.cc",
    "core/providers/cuda/nn/conv_transpose.cc",
    "core/providers/cuda/nn/deform_conv.cc",
    "core/providers/cuda/nn/dropout.cc",
    "core/providers/cuda/nn/instance_norm.cc",
    "core/providers/cuda/nn/layer_norm.cc",
    "core/providers/cuda/nn/lp_norm.cc",
    "core/providers/cuda/nn/lrn.cc",
    "core/providers/cuda/nn/pool.cc",
    "core/providers/cuda/nn/rms_norm.cc",
    "core/providers/cuda/nn/shrink.cc",
    "core/providers/cuda/nvtx_profile.cc",
    "core/providers/cuda/object_detection/non_max_suppression.cc",
    "core/providers/cuda/object_detection/roialign.cc",
    "core/providers/cuda/reduction/reduction_functions.cc",
    "core/providers/cuda/reduction/reduction_ops.cc",
    "core/providers/cuda/rnn/cudnn_rnn_base.cc",
    "core/providers/cuda/rnn/gru.cc",
    "core/providers/cuda/rnn/lstm.cc",
    "core/providers/cuda/rnn/rnn.cc",
    "core/providers/cuda/tensor/cast_op.cc",
    "core/providers/cuda/tensor/compress.cc",
    "core/providers/cuda/tensor/concat.cc",
    "core/providers/cuda/tensor/expand.cc",
    "core/providers/cuda/tensor/eye_like.cc",
    "core/providers/cuda/tensor/flatten.cc",
    "core/providers/cuda/tensor/gather.cc",
    "core/providers/cuda/tensor/gather_elements.cc",
    "core/providers/cuda/tensor/gather_nd.cc",
    "core/providers/cuda/tensor/gelu.cc",
    "core/providers/cuda/tensor/grid_sample.cc",
    "core/providers/cuda/tensor/identity_op.cc",
    "core/providers/cuda/tensor/nonzero_op.cc",
    "core/providers/cuda/tensor/onehot.cc",
    "core/providers/cuda/tensor/pad.cc",
    "core/providers/cuda/tensor/quantize_linear.cc",
    "core/providers/cuda/tensor/reshape.cc",
    "core/providers/cuda/tensor/resize.cc",
    "core/providers/cuda/tensor/reverse_sequence.cc",
    "core/providers/cuda/tensor/scatter_elements.cc",
    "core/providers/cuda/tensor/scatter_nd.cc",
    "core/providers/cuda/tensor/sequence_op.cc",
    "core/providers/cuda/tensor/shape_op.cc",
    "core/providers/cuda/tensor/size.cc",
    "core/providers/cuda/tensor/slice.cc",
    "core/providers/cuda/tensor/space_depth_ops.cc",
    "core/providers/cuda/tensor/split.cc",
    "core/providers/cuda/tensor/squeeze.cc",
    "core/providers/cuda/tensor/tile.cc",
    "core/providers/cuda/tensor/transpose.cc",
    "core/providers/cuda/tensor/trilu.cc",
    "core/providers/cuda/tensor/unsqueeze.cc",
    "core/providers/cuda/tensor/upsample.cc",
    "core/providers/cuda/tensor/where.cc",
    "core/providers/cuda/tunable/cuda_tuning_context.cc",
    "core/providers/cuda/tunable/math/gemm.cc",
    "core/providers/cuda/tunable/math/matmul.cc",
    "core/providers/cuda/tunable/util.cc",
};

/// The device half: every `.cu` under the same two trees, compiled by nvcc
/// rather than by Zig, since nothing else emits device code.
pub const ort_cuda_device_sources = [_][]const u8{
    "contrib_ops/cuda/activation/activations_impl.cu",
    "contrib_ops/cuda/bert/add_bias_transpose.cu",
    "contrib_ops/cuda/bert/attention_impl.cu",
    "contrib_ops/cuda/bert/attention_kv_cache.cu",
    "contrib_ops/cuda/bert/attention_prepare_qkv.cu",
    "contrib_ops/cuda/bert/attention_qk.cu",
    "contrib_ops/cuda/bert/attention_softmax.cu",
    "contrib_ops/cuda/bert/attention_strided_copy.cu",
    "contrib_ops/cuda/bert/attention_transpose.cu",
    "contrib_ops/cuda/bert/bert_padding.cu",
    "contrib_ops/cuda/bert/causal_conv_with_state_impl.cu",
    "contrib_ops/cuda/bert/cutlass_fmha/fmha_sm50.cu",
    "contrib_ops/cuda/bert/cutlass_fmha/fmha_sm70.cu",
    "contrib_ops/cuda/bert/cutlass_fmha/fmha_sm75.cu",
    "contrib_ops/cuda/bert/cutlass_fmha/fmha_sm80.cu",
    "contrib_ops/cuda/bert/cutlass_fmha/memory_efficient_attention.cu",
    "contrib_ops/cuda/bert/decoder_attention_impl.cu",
    "contrib_ops/cuda/bert/embed_layer_norm_impl.cu",
    "contrib_ops/cuda/bert/fastertransformer_decoder_attention/decoder_masked_multihead_attention_impl.cu",
    "contrib_ops/cuda/bert/flash_attention/flash_fwd_hdim128_bf16_causal_sm80.cu",
    "contrib_ops/cuda/bert/flash_attention/flash_fwd_hdim128_bf16_sm80.cu",
    "contrib_ops/cuda/bert/flash_attention/flash_fwd_hdim128_fp16_causal_sm80.cu",
    "contrib_ops/cuda/bert/flash_attention/flash_fwd_hdim128_fp16_sm80.cu",
    "contrib_ops/cuda/bert/flash_attention/flash_fwd_hdim192_bf16_causal_sm80.cu",
    "contrib_ops/cuda/bert/flash_attention/flash_fwd_hdim192_bf16_sm80.cu",
    "contrib_ops/cuda/bert/flash_attention/flash_fwd_hdim192_fp16_causal_sm80.cu",
    "contrib_ops/cuda/bert/flash_attention/flash_fwd_hdim192_fp16_sm80.cu",
    "contrib_ops/cuda/bert/flash_attention/flash_fwd_hdim256_bf16_causal_sm80.cu",
    "contrib_ops/cuda/bert/flash_attention/flash_fwd_hdim256_bf16_sm80.cu",
    "contrib_ops/cuda/bert/flash_attention/flash_fwd_hdim256_fp16_causal_sm80.cu",
    "contrib_ops/cuda/bert/flash_attention/flash_fwd_hdim256_fp16_sm80.cu",
    "contrib_ops/cuda/bert/flash_attention/flash_fwd_hdim32_bf16_causal_sm80.cu",
    "contrib_ops/cuda/bert/flash_attention/flash_fwd_hdim32_bf16_sm80.cu",
    "contrib_ops/cuda/bert/flash_attention/flash_fwd_hdim32_fp16_causal_sm80.cu",
    "contrib_ops/cuda/bert/flash_attention/flash_fwd_hdim32_fp16_sm80.cu",
    "contrib_ops/cuda/bert/flash_attention/flash_fwd_hdim64_bf16_causal_sm80.cu",
    "contrib_ops/cuda/bert/flash_attention/flash_fwd_hdim64_bf16_sm80.cu",
    "contrib_ops/cuda/bert/flash_attention/flash_fwd_hdim64_fp16_causal_sm80.cu",
    "contrib_ops/cuda/bert/flash_attention/flash_fwd_hdim64_fp16_sm80.cu",
    "contrib_ops/cuda/bert/flash_attention/flash_fwd_hdim96_bf16_causal_sm80.cu",
    "contrib_ops/cuda/bert/flash_attention/flash_fwd_hdim96_bf16_sm80.cu",
    "contrib_ops/cuda/bert/flash_attention/flash_fwd_hdim96_fp16_causal_sm80.cu",
    "contrib_ops/cuda/bert/flash_attention/flash_fwd_hdim96_fp16_sm80.cu",
    "contrib_ops/cuda/bert/flash_attention/flash_fwd_split_hdim128_bf16_causal_sm80.cu",
    "contrib_ops/cuda/bert/flash_attention/flash_fwd_split_hdim128_bf16_sm80.cu",
    "contrib_ops/cuda/bert/flash_attention/flash_fwd_split_hdim128_fp16_causal_sm80.cu",
    "contrib_ops/cuda/bert/flash_attention/flash_fwd_split_hdim128_fp16_sm80.cu",
    "contrib_ops/cuda/bert/flash_attention/flash_fwd_split_hdim192_bf16_causal_sm80.cu",
    "contrib_ops/cuda/bert/flash_attention/flash_fwd_split_hdim192_bf16_sm80.cu",
    "contrib_ops/cuda/bert/flash_attention/flash_fwd_split_hdim192_fp16_causal_sm80.cu",
    "contrib_ops/cuda/bert/flash_attention/flash_fwd_split_hdim192_fp16_sm80.cu",
    "contrib_ops/cuda/bert/flash_attention/flash_fwd_split_hdim256_bf16_causal_sm80.cu",
    "contrib_ops/cuda/bert/flash_attention/flash_fwd_split_hdim256_bf16_sm80.cu",
    "contrib_ops/cuda/bert/flash_attention/flash_fwd_split_hdim256_fp16_causal_sm80.cu",
    "contrib_ops/cuda/bert/flash_attention/flash_fwd_split_hdim256_fp16_sm80.cu",
    "contrib_ops/cuda/bert/flash_attention/flash_fwd_split_hdim32_bf16_causal_sm80.cu",
    "contrib_ops/cuda/bert/flash_attention/flash_fwd_split_hdim32_bf16_sm80.cu",
    "contrib_ops/cuda/bert/flash_attention/flash_fwd_split_hdim32_fp16_causal_sm80.cu",
    "contrib_ops/cuda/bert/flash_attention/flash_fwd_split_hdim32_fp16_sm80.cu",
    "contrib_ops/cuda/bert/flash_attention/flash_fwd_split_hdim64_bf16_causal_sm80.cu",
    "contrib_ops/cuda/bert/flash_attention/flash_fwd_split_hdim64_bf16_sm80.cu",
    "contrib_ops/cuda/bert/flash_attention/flash_fwd_split_hdim64_fp16_causal_sm80.cu",
    "contrib_ops/cuda/bert/flash_attention/flash_fwd_split_hdim64_fp16_sm80.cu",
    "contrib_ops/cuda/bert/flash_attention/flash_fwd_split_hdim96_bf16_causal_sm80.cu",
    "contrib_ops/cuda/bert/flash_attention/flash_fwd_split_hdim96_bf16_sm80.cu",
    "contrib_ops/cuda/bert/flash_attention/flash_fwd_split_hdim96_fp16_causal_sm80.cu",
    "contrib_ops/cuda/bert/flash_attention/flash_fwd_split_hdim96_fp16_sm80.cu",
    "contrib_ops/cuda/bert/gated_add_impl.cu",
    "contrib_ops/cuda/bert/gemma_rotary_emb_impl.cu",
    "contrib_ops/cuda/bert/group_query_attention_impl.cu",
    "contrib_ops/cuda/bert/lean_attention/lean_fwd_hdim128_fp16.cu",
    "contrib_ops/cuda/bert/lean_attention/lean_fwd_hdim64_fp16.cu",
    "contrib_ops/cuda/bert/linear_attention_gates_impl.cu",
    "contrib_ops/cuda/bert/linear_attention_impl.cu",
    "contrib_ops/cuda/bert/longformer_attention_impl.cu",
    "contrib_ops/cuda/bert/longformer_attention_softmax.cu",
    "contrib_ops/cuda/bert/longformer_global_impl.cu",
    "contrib_ops/cuda/bert/mrotary_embedding_impl.cu",
    "contrib_ops/cuda/bert/ngram_repeat_block_impl.cu",
    "contrib_ops/cuda/bert/packed_attention_impl.cu",
    "contrib_ops/cuda/bert/packed_multihead_attention_impl.cu",
    "contrib_ops/cuda/bert/paged_attention_impl.cu",
    "contrib_ops/cuda/bert/relative_attn_bias_impl.cu",
    "contrib_ops/cuda/bert/rotary_embedding_impl.cu",
    "contrib_ops/cuda/bert/skip_layer_norm_impl.cu",
    "contrib_ops/cuda/bert/tensorrt_fused_multihead_attention/mha_runner.cu",
    "contrib_ops/cuda/bert/unfused_attention.cu",
    "contrib_ops/cuda/bert/xqa/xqa_loader_bf16_128.cu",
    "contrib_ops/cuda/bert/xqa/xqa_loader_bf16_256.cu",
    "contrib_ops/cuda/bert/xqa/xqa_loader_bf16_64.cu",
    "contrib_ops/cuda/bert/xqa/xqa_loader_bf16.cu",
    "contrib_ops/cuda/bert/xqa/xqa_loader_bf16_fp8_128.cu",
    "contrib_ops/cuda/bert/xqa/xqa_loader_bf16_fp8_256.cu",
    "contrib_ops/cuda/bert/xqa/xqa_loader_bf16_fp8_64.cu",
    "contrib_ops/cuda/bert/xqa/xqa_loader_bf16_int8_128.cu",
    "contrib_ops/cuda/bert/xqa/xqa_loader_bf16_int8_256.cu",
    "contrib_ops/cuda/bert/xqa/xqa_loader_bf16_int8_64.cu",
    "contrib_ops/cuda/bert/xqa/xqa_loader_bf16_int8.cu",
    "contrib_ops/cuda/bert/xqa/xqa_loader_fp16_128.cu",
    "contrib_ops/cuda/bert/xqa/xqa_loader_fp16_256.cu",
    "contrib_ops/cuda/bert/xqa/xqa_loader_fp16_64.cu",
    "contrib_ops/cuda/bert/xqa/xqa_loader_fp16.cu",
    "contrib_ops/cuda/bert/xqa/xqa_loader_fp16_fp8_128.cu",
    "contrib_ops/cuda/bert/xqa/xqa_loader_fp16_fp8_256.cu",
    "contrib_ops/cuda/bert/xqa/xqa_loader_fp16_fp8_64.cu",
    "contrib_ops/cuda/bert/xqa/xqa_loader_fp16_int8_128.cu",
    "contrib_ops/cuda/bert/xqa/xqa_loader_fp16_int8_256.cu",
    "contrib_ops/cuda/bert/xqa/xqa_loader_fp16_int8_64.cu",
    "contrib_ops/cuda/bert/xqa/xqa_loader_fp16_int8.cu",
    "contrib_ops/cuda/bert/xqa/xqa_paged_bf16_fp8_128.cu",
    "contrib_ops/cuda/bert/xqa/xqa_paged_bf16_fp8_64.cu",
    "contrib_ops/cuda/bert/xqa/xqa_paged_bf16_int8_128.cu",
    "contrib_ops/cuda/bert/xqa/xqa_paged_bf16_int8_64.cu",
    "contrib_ops/cuda/bert/xqa/xqa_paged_fp16_fp8_128.cu",
    "contrib_ops/cuda/bert/xqa/xqa_paged_fp16_fp8_64.cu",
    "contrib_ops/cuda/bert/xqa/xqa_paged_fp16_int8_128.cu",
    "contrib_ops/cuda/bert/xqa/xqa_paged_fp16_int8_64.cu",
    "contrib_ops/cuda/bert/xqa/xqa_paged_loader.cu",
    "contrib_ops/cuda/diffusion/bias_add_impl.cu",
    "contrib_ops/cuda/diffusion/bias_split_gelu_impl.cu",
    "contrib_ops/cuda/diffusion/group_norm_impl.cu",
    "contrib_ops/cuda/llm/fpA_intB_gemm_adaptor.cu",
    "contrib_ops/cuda/llm/fpA_intB_gemm/bf16_int4_gemm_scaleonly.cu",
    "contrib_ops/cuda/llm/fpA_intB_gemm/bf16_int4_gemm_scale_zeros.cu",
    "contrib_ops/cuda/llm/fpA_intB_gemm/bf16_int8_gemm_scaleonly.cu",
    "contrib_ops/cuda/llm/fpA_intB_gemm/bf16_int8_gemm_scale_zeros.cu",
    "contrib_ops/cuda/llm/fpA_intB_gemm/fp16_int4_gemm_scaleonly.cu",
    "contrib_ops/cuda/llm/fpA_intB_gemm/fp16_int4_gemm_scale_zeros.cu",
    "contrib_ops/cuda/llm/fpA_intB_gemm/fp16_int8_gemm_scaleonly.cu",
    "contrib_ops/cuda/llm/fpA_intB_gemm/fp16_int8_gemm_scale_zeros.cu",
    "contrib_ops/cuda/llm/fpA_intB_gemm/launchers/fpA_intB_gemm_launcher_10.generated.cu",
    "contrib_ops/cuda/llm/fpA_intB_gemm/launchers/fpA_intB_gemm_launcher_11.generated.cu",
    "contrib_ops/cuda/llm/fpA_intB_gemm/launchers/fpA_intB_gemm_launcher_12.generated.cu",
    "contrib_ops/cuda/llm/fpA_intB_gemm/launchers/fpA_intB_gemm_launcher_13.generated.cu",
    "contrib_ops/cuda/llm/fpA_intB_gemm/launchers/fpA_intB_gemm_launcher_14.generated.cu",
    "contrib_ops/cuda/llm/fpA_intB_gemm/launchers/fpA_intB_gemm_launcher_15.generated.cu",
    "contrib_ops/cuda/llm/fpA_intB_gemm/launchers/fpA_intB_gemm_launcher_16.generated.cu",
    "contrib_ops/cuda/llm/fpA_intB_gemm/launchers/fpA_intB_gemm_launcher_1.generated.cu",
    "contrib_ops/cuda/llm/fpA_intB_gemm/launchers/fpA_intB_gemm_launcher_2.generated.cu",
    "contrib_ops/cuda/llm/fpA_intB_gemm/launchers/fpA_intB_gemm_launcher_3.generated.cu",
    "contrib_ops/cuda/llm/fpA_intB_gemm/launchers/fpA_intB_gemm_launcher_4.generated.cu",
    "contrib_ops/cuda/llm/fpA_intB_gemm/launchers/fpA_intB_gemm_launcher_5.generated.cu",
    "contrib_ops/cuda/llm/fpA_intB_gemm/launchers/fpA_intB_gemm_launcher_6.generated.cu",
    "contrib_ops/cuda/llm/fpA_intB_gemm/launchers/fpA_intB_gemm_launcher_7.generated.cu",
    "contrib_ops/cuda/llm/fpA_intB_gemm/launchers/fpA_intB_gemm_launcher_8.generated.cu",
    "contrib_ops/cuda/llm/fpA_intB_gemm/launchers/fpA_intB_gemm_launcher_9.generated.cu",
    "contrib_ops/cuda/llm/fpA_intB_gemm_preprocessors_impl.cu",
    "contrib_ops/cuda/llm/fpA_intB_gemv/dispatcher_bf16_int4.cu",
    "contrib_ops/cuda/llm/fpA_intB_gemv/dispatcher_bf16_int4_hopper.cu",
    "contrib_ops/cuda/llm/fpA_intB_gemv/dispatcher_bf16_int8.cu",
    "contrib_ops/cuda/llm/fpA_intB_gemv/dispatcher_bf16_int8_hopper.cu",
    "contrib_ops/cuda/llm/fpA_intB_gemv/dispatcher_fp16_int4.cu",
    "contrib_ops/cuda/llm/fpA_intB_gemv/dispatcher_fp16_int4_hopper.cu",
    "contrib_ops/cuda/llm/fpA_intB_gemv/dispatcher_fp16_int8.cu",
    "contrib_ops/cuda/llm/fpA_intB_gemv/dispatcher_fp16_int8_hopper.cu",
    "contrib_ops/cuda/llm/fpA_intB_gemv/fpA_intB_gemv.cu",
    "contrib_ops/cuda/llm/kernels/pre_quant_scale_kernel.cu",
    "contrib_ops/cuda/llm/moe_gemm/launchers/fused_moe_gemm_sm80_bf16_m128_n128_k64.generated.cu",
    "contrib_ops/cuda/llm/moe_gemm/launchers/fused_moe_gemm_sm80_bf16_m16_n128_k64.generated.cu",
    "contrib_ops/cuda/llm/moe_gemm/launchers/fused_moe_gemm_sm80_bf16_m16_n256_k64.generated.cu",
    "contrib_ops/cuda/llm/moe_gemm/launchers/fused_moe_gemm_sm80_bf16_m32_n128_k64.generated.cu",
    "contrib_ops/cuda/llm/moe_gemm/launchers/fused_moe_gemm_sm80_bf16_m64_n128_k64.generated.cu",
    "contrib_ops/cuda/llm/moe_gemm/launchers/fused_moe_gemm_sm80_f16_m128_n128_k64.generated.cu",
    "contrib_ops/cuda/llm/moe_gemm/launchers/fused_moe_gemm_sm80_f16_m16_n128_k64.generated.cu",
    "contrib_ops/cuda/llm/moe_gemm/launchers/fused_moe_gemm_sm80_f16_m16_n256_k64.generated.cu",
    "contrib_ops/cuda/llm/moe_gemm/launchers/fused_moe_gemm_sm80_f16_m32_n128_k64.generated.cu",
    "contrib_ops/cuda/llm/moe_gemm/launchers/fused_moe_gemm_sm80_f16_m64_n128_k64.generated.cu",
    "contrib_ops/cuda/llm/moe_gemm/launchers/moe_gemm_tma_ws_sm90_bf16.generated.cu",
    "contrib_ops/cuda/llm/moe_gemm/launchers/moe_gemm_tma_ws_sm90_f16.generated.cu",
    "contrib_ops/cuda/llm/moe_gemm/moe_gemm_kernels_bf16_bf16.cu",
    "contrib_ops/cuda/llm/moe_gemm/moe_gemm_kernels_bf16_uint4.cu",
    "contrib_ops/cuda/llm/moe_gemm/moe_gemm_kernels_bf16_uint8.cu",
    "contrib_ops/cuda/llm/moe_gemm/moe_gemm_kernels_fp16_fp16.cu",
    "contrib_ops/cuda/llm/moe_gemm/moe_gemm_kernels_fp16_uint4.cu",
    "contrib_ops/cuda/llm/moe_gemm/moe_gemm_kernels_fp16_uint8.cu",
    "contrib_ops/cuda/llm/moe_gemm/moe_gemm_kernels_fp32_fp32.cu",
    "contrib_ops/cuda/llm/moe_gemm/moe_gemm_tma_warp_specialized_input.cu",
    "contrib_ops/cuda/llm/moe_gemm/moe_gemv.cu",
    "contrib_ops/cuda/llm/moe_gemm/moe_gemv_fp4.cu",
    "contrib_ops/cuda/llm/moe_gemm/moe_kernels.cu",
    "contrib_ops/cuda/math/bias_dropout_impl.cu",
    "contrib_ops/cuda/math/bias_gelu_impl.cu",
    "contrib_ops/cuda/math/bias_softmax_impl.cu",
    "contrib_ops/cuda/math/complex_mul_impl.cu",
    "contrib_ops/cuda/math/fft_ops_impl.cu",
    "contrib_ops/cuda/math/gemm_float8.cu",
    "contrib_ops/cuda/math/isfinite_impl.cu",
    "contrib_ops/cuda/math/matmul_block_scaled_fp4.cu",
    "contrib_ops/cuda/math/matmul_block_scaled_fp8.cu",
    "contrib_ops/cuda/moe/qmoe_kernels.cu",
    "contrib_ops/cuda/quantization/attention_quantization_impl.cu",
    "contrib_ops/cuda/quantization/dequantize_blockwise_4bits.cu",
    "contrib_ops/cuda/quantization/dequantize_blockwise_8bits.cu",
    "contrib_ops/cuda/quantization/dequantize_blockwise_bnb4.cu",
    "contrib_ops/cuda/quantization/gather_block_quantized.cu",
    "contrib_ops/cuda/quantization/matmul_4bits_batched_bfloat16.cu",
    "contrib_ops/cuda/quantization/matmul_4bits_batched_half.cu",
    "contrib_ops/cuda/quantization/matmul_4bits_bfloat16.cu",
    "contrib_ops/cuda/quantization/matmul_4bits.cu",
    "contrib_ops/cuda/quantization/matmul_4bits_float.cu",
    "contrib_ops/cuda/quantization/matmul_4bits_half.cu",
    "contrib_ops/cuda/quantization/matmul_8bits_batched_bfloat16.cu",
    "contrib_ops/cuda/quantization/matmul_8bits_batched_float.cu",
    "contrib_ops/cuda/quantization/matmul_8bits_batched_half.cu",
    "contrib_ops/cuda/quantization/matmul_8bits_bfloat16.cu",
    "contrib_ops/cuda/quantization/matmul_8bits.cu",
    "contrib_ops/cuda/quantization/matmul_8bits_float.cu",
    "contrib_ops/cuda/quantization/matmul_8bits_half.cu",
    "contrib_ops/cuda/quantization/matmul_bnb4.cu",
    "contrib_ops/cuda/quantization/qordered_ops/qordered_attention_impl.cu",
    "contrib_ops/cuda/quantization/qordered_ops/qordered_layer_norm_impl.cu",
    "contrib_ops/cuda/quantization/qordered_ops/qordered_qdq_impl.cu",
    "contrib_ops/cuda/quantization/qordered_ops/qordered_unary_ops_impl.cu",
    "contrib_ops/cuda/sparse/block_mask.cu",
    "contrib_ops/cuda/sparse/sparse_attention_impl.cu",
    "contrib_ops/cuda/tensor/crop_impl.cu",
    "contrib_ops/cuda/tensor/dynamic_time_warping_impl.cu",
    "contrib_ops/cuda/tensor/image_scaler_impl.cu",
    "contrib_ops/cuda/tensor/unfold_impl.cu",
    "contrib_ops/cuda/transformers/beam_search_topk.cu",
    "contrib_ops/cuda/transformers/generation_cuda_impl.cu",
    "contrib_ops/cuda/transformers/greedy_search_top_one.cu",
    "core/providers/cuda/activation/activations_impl.cu",
    "core/providers/cuda/cuda_utils.cu",
    "core/providers/cuda/fpgeneric.cu",
    "core/providers/cuda/generator/random_impl.cu",
    "core/providers/cuda/generator/range_impl.cu",
    "core/providers/cuda/llm/attention_mask_impl.cu",
    "core/providers/cuda/llm/rotary_embedding_impl.cu",
    "core/providers/cuda/llm/tensorscatter_impl.cu",
    "core/providers/cuda/math/binary_elementwise_ops_impl.cu",
    "core/providers/cuda/math/clip_impl.cu",
    "core/providers/cuda/math/cumsum_impl.cu",
    "core/providers/cuda/math/einsum_utils/einsum_auxiliary_ops_diagonal.cu",
    "core/providers/cuda/math/matmul_integer.cu",
    "core/providers/cuda/math/softmax_impl.cu",
    "core/providers/cuda/math/topk_impl_bf16.cu",
    "core/providers/cuda/math/topk_impl_f16.cu",
    "core/providers/cuda/math/topk_impl_f32.cu",
    "core/providers/cuda/math/topk_impl_f64.cu",
    "core/providers/cuda/math/topk_impl_i16.cu",
    "core/providers/cuda/math/topk_impl_i32.cu",
    "core/providers/cuda/math/topk_impl_i64.cu",
    "core/providers/cuda/math/topk_impl_i8.cu",
    "core/providers/cuda/math/topk_impl_u8.cu",
    "core/providers/cuda/math/unary_elementwise_ops_impl.cu",
    "core/providers/cuda/math/variadic_elementwise_ops_impl.cu",
    "core/providers/cuda/ml/label_encoder_impl.cu",
    "core/providers/cuda/nn/avg_pool_impl.cu",
    "core/providers/cuda/nn/deform_conv_impl.cu",
    "core/providers/cuda/nn/dropout_impl.cu",
    "core/providers/cuda/nn/instance_norm_impl.cu",
    "core/providers/cuda/nn/layer_norm_impl.cu",
    "core/providers/cuda/nn/lp_norm_impl.cu",
    "core/providers/cuda/nn/max_pool_with_index.cu",
    "core/providers/cuda/nn/shrink_impl.cu",
    "core/providers/cuda/object_detection/non_max_suppression_impl.cu",
    "core/providers/cuda/object_detection/roialign_impl.cu",
    "core/providers/cuda/reduction/reduction_functions.cu",
    "core/providers/cuda/rnn/rnn_impl.cu",
    "core/providers/cuda/tensor/cast_op.cu",
    "core/providers/cuda/tensor/compress_impl.cu",
    "core/providers/cuda/tensor/concat_impl.cu",
    "core/providers/cuda/tensor/expand_impl.cu",
    "core/providers/cuda/tensor/eye_like_impl.cu",
    "core/providers/cuda/tensor/gather_elements_impl.cu",
    "core/providers/cuda/tensor/gather_impl.cu",
    "core/providers/cuda/tensor/gather_nd_impl.cu",
    "core/providers/cuda/tensor/gelu_approximate_impl.cu",
    "core/providers/cuda/tensor/gelu_impl.cu",
    "core/providers/cuda/tensor/grid_sample_impl.cu",
    "core/providers/cuda/tensor/nonzero_impl.cu",
    "core/providers/cuda/tensor/onehot.cu",
    "core/providers/cuda/tensor/pad_impl.cu",
    "core/providers/cuda/tensor/quantize_linear.cu",
    "core/providers/cuda/tensor/resize_antialias_impl.cu",
    "core/providers/cuda/tensor/resize_impl.cu",
    "core/providers/cuda/tensor/reverse_sequence_impl.cu",
    "core/providers/cuda/tensor/scatter_nd_impl.cu",
    "core/providers/cuda/tensor/slice_impl.cu",
    "core/providers/cuda/tensor/split_impl.cu",
    "core/providers/cuda/tensor/tile_impl.cu",
    "core/providers/cuda/tensor/transpose_impl.cu",
    "core/providers/cuda/tensor/trilu_impl.cu",
    "core/providers/cuda/tensor/upsample_impl.cu",
    "core/providers/cuda/tensor/where_impl.cu",
    "core/providers/cuda/triton_kernel.cu",
};
